### ISSUE TITLE
Monthly Mycetoma Meeting 29th August 2023

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMycetoma/Monthly-zoom-meetings#10]
Time: Aug 29th (12 noon UK, 1pm EU, 9pm Aus) [Timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=8&day=29&hour=11&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=152&p10=240).

The Outlook invite can be found [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/files/9674081/Monthly.MycetOS.meeting00.zip)

Location: https://uni-sydney.zoom.us/j/99281549497. In case of failure, use https://ucl.zoom.us/j/99789829423 and in case of double failure use [MycetOS meeting teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2I2MDcxZTgtYjZjOS00YTdmLTgwZTMtNWQ3OTc4NDY0MDNj%40thread.v2/0?context=%7b%22Tid%22%3a%22526638ba-6af3-4b0f-a532-a1a511f4ac80%22%2c%22Oid%22%3a%22a5ed84b8-5af1-42c6-9f8d-240f23a5d997%22%7d)
Chair: USyd
Minute taker: UCL
Previous meeting: #7 
Recording: [here](https://youtu.be/wzbRzA6anBQ)
Present: 
Apologies: @mattodd 

AGENDA

### Series 1 - Fenarimols

_Final Molecules/SAR Gaps_

[@fantasy121 completed the selection of Epichem molecules](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1530752314), and the next step is to get them to Wendy.

@fantasy121 shared [the list of compounds that have been shipped from Sydney to ErasmusMC](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1542026215). 

- [x] @MA-Jjingyi to evaluate these latest fenarimols and post data to the Master List, though there is a delay because of a problem at the production site for larvae.

- [ ] @mattodd is in touch with Epichem (Martine was on vacation) and will email the finalised list to them.

- [ ] @meh-cyprian to proceed to try to model fenarimol compounds in potential protein target [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/68#issuecomment-1546869698), or to clarify what more data are needed. Aim is to better understand the SAR via docking vs homology model of protein.

_Paper:_

- [ ] @dmitrij176 to upload offline copy of fenarimol lab notebook to UCL respository and provide link (@fantasy121 is https://doi.org/10.25910/CS81-G976). @mattodd to assist with copying data over.
- [x] @MA-Jjingyi @wwjvdsande generate an offline excell sheet with all the fenarimol screening data. 
- [x] @dosreic add the final logD data to the mastertable, entries were sent via e-mail by @wwjvdsande to make the entry in the software easier
- [ ] @dmitrij176 @fantasy121 @mattodd check supplementary table made by @wwjvdsande 
- [x] @wwjvdsande corrected figures and references in the manuscript
- [x] @dmitrij176 to make corrections to manuscript.
- [ ] @fantasy121 to make corrections to manuscript.

MYOS codes to be used for the compounds, to maintain the link between compounds in the paper and compounds in the live project. The codes needed are just the initial integers, not the batch/salt codes etc. Can also remove zeroes for readability, so e.g. MYOS7.

_Siderophores:_

New transcriptomic data from @wwjvdsande in the galleria grain model showed that siderophores are produced (https://github.com/OpenSourceMycetoma/What-other-molecules-to-screen/issues/10). These siderophores might be used as a trojan horse to get molecules into the grain. Could we couple fenarimols to fungal-relevant siderophores may be to get them in? The idea of the siderophores was of interest and all partners agreed to consider whether this could be done at the different sites. There is also potential relevance to other series. 

- [ ] @OpenSourceMycetoma/corecontrib to report back on potential structures (in the original issue https://github.com/OpenSourceMycetoma/What-other-molecules-to-screen/issues/10) and ways they might be produced within the resources available.
- [x] @wwjvdsande to pursue a link with Prof Doyle in Ireland who might be able to attach a fluorophore to a siderophore that would permit assessment of whether the siderophore transported the fluorophore into the grain.

### Series 2 - Aminothiazoles

@KlementineJBS is the corresponding researcher for this project at USyd. @KlementineJBS has updated the [Wiki](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/All-Compounds-Made-To-Date) with the compounds successfully synthesised by USyd in June.

UCL Masters student cohort began in late May and has now (late July) finished their synthetic work.

- [ ] @mattodd to organise next meeting of this group needs to be organised, e.g. July?
- [x] @dmitrij176 to obtain list of samples made by UCL MSc cohort, and obtain the samples themselves.
- [x] #11
- [ ] @AndyBishopSevenoaks @JuliaSarju are there any samples likely to be incoming?
- [ ] @dosreic to try to secure samples related to this paper https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11 ?
- [ ] @KlementineJBS to consider an edit to the Master List and report back: Generally we are not doing well at keeping track of who is making what. We need contributors to clarify their targets, and these should be included in the Master List as targets, where the "target" tag can be changed upon successful synthesis. Ideally to include a link to the URL where the molecule was suggested or discussed.

### Series 5 - Benzimidazoles

The related oxazoles:
Good potencies observed for recent compound batches (e.g. [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/82#issuecomment-1325150305)). These resemble the benzimidazoles which have shown potent in vivo efficacy. Some oxazoles will be tested against _Falciformispora senegalensis_ too. This series will be evaluated _in vivo_ in the new larval season.

- [ ] @dosreic to try to obtain samples.
- [ ] @memm0740 to search for whether additional samples could be obtained from other labs.
- [ ] @AndreaOtago to clarify whether the [new set of benzoxazoles](https://github.com/OpenSourceMycetoma/series-5-benzimidazoles/issues/3#issuecomment-1556652617) has been shipped to @wwjvdsande.
- [ ]  @fantasy121 to ask Sydney Hons students Peiyan to join Github and share ID.
- [ ] @memm0740 to update on progress of synthesis. Done [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/7#issuecomment-1622784020). @memm0740 to post link to raw data on ELN.

### Series 6: ketoximes

Latest compound shipment [here](https://github.com/OpenSourceMycetoma/Series-6-Ketoximes/issues/5), to be tested by @MA-Jjingyi. 

@dmitrij176  has obtained a crystal structure for one of the isomers of one of the Series 6 compounds. Separated isomers have been sent to @MA-Jjingyi to see whether they have different potencies. @dmitrij176 is now engaged in experiments to evaluate the conditions under which the isomers interconvert.

@bebi78 suggested evaluating different salts of the ketoximes.

### Series 3: Tricyclics/Phenothiazines
- [ ] @wwjvdsande and @lferrins to arrange for shipment of compounds - issue page here: https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6
- [ ] @JuliaSarju to see if she can get a student or two to make 100mg or so of N-phenethylphenothiazine (CAS NUMBER  68825-26-3)

### Misc updates:

DMPK measurements by Dundee. Compound selection taking place in #8. 

- [x]  MMV Global Health Priority Box screened against _Madurella mycetomatis_ and _Falciformispora senegalensis_. Led to the identification of promising hits [MMV1593278, MMV1804559 and MMV020335](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/6#issuecomment-1567312472). @MA-Jjingyi to evaluate these compounds in the _in vivo_ model.

- [ ] @memm0740 to enter the data for [Rohan Davies' compounds](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/84#issuecomment-1507518700) into the Master List. They need [MyOS codes](https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/The-Molecule-Numbering-Convention).

- [x] Kinase inhibitor library. The updated KCGS library was ordered on 1st of May. It has arrived in Erasmus MC. Bio-informatical analyses have been carried out by Mickey. @bebi78 can send some 10 targets. Mickey screened this last week for the first time, repeat is scheduled for this week.

Bioinformatics: Waleed requested information on which aspect of bioinformatics should be prioritised to work on first. @wwjvdsande corresponded offline with him. This will include a Phylogenetic tree to work out relationships of various species were identified as high priorities so that we can search the literature for closely related species to Mycetoma, and for the potential structures of the drug target, which would enable us to simulate our data/estimation/computational models. In the May meeting @TariqAyub attended from the Qasim group who will advise on what can be done in terms of future contributions.

### Minutes

**Manuscript writing** 
Paper editing is underway and needs final corrections from Dmitrij and Hung.
Wendy has cleared all of the corrections and needs to edit some figures after other project members double check and finalise the correct list of Fenarimols in the paper.
Currently there is a mismatch in numbers of analogues between the SI excel file and the the manuscript.

Previously there has been an agreed cut off point of Fenarimols for the paper which means that novel potency data from Series 1 will not be included.

Remaining paper objectives:

- [ ]  @dmitrij176 to upload offline copy of fenarimol lab notebook to UCL respository and provide link (@fantasy121 is https://doi.org/10.25910/CS81-G976). @mattodd to assist with copying data over.
- [ ] @dmitrij176 @fantasy121 @mattodd check supplementary table made by @wwjvdsande
- [ ] @dmitrij176 to make final corrections to manuscript.
- [ ] @fantasy121 to make final corrections to manuscript.
- [ ] MYOS code addition. MYOS codes to be used for the compounds, to maintain the link between compounds in the paper and compounds in the live project. The codes needed are just the initial integers, not the batch/salt codes etc. Can also remove zeroes for readability, so e.g. MYOS7. @dmitrij176 and @fantasy121 to double check.
- [ ] References need to be sorted after final manuscript review. There is a recurring compatibility issue when editing via Dropbox. 

**Siderophores**
Wendy has spoken on the subject with Prof Doyle from Ireland. More information on siderophore studies to follow soon.

 - [ ] @OpenSourceMycetoma/corecontrib to report back on potential structures (in the original issue https://github.com/OpenSourceMycetoma/What-other-molecules-to-screen/issues/10) and ways they might be produced within the resources available

**Series 2 Aminothiazoles**
Molecules made by UCL MSc cohort (**23 entries**) have been shipped to Erasmus MC for testing. Same applies for selected Whitgift compound (MYOS_0590_00_01).

- [ ] @mattodd to organise next meeting of this group; needs to be organised sometime in the new term.
- [ ] @AndyBishopSevenoaks @JuliaSarju are there any samples likely to be incoming?
- [ ] @dosreic to try to secure samples related to this paper https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11 ?
- [ ] @KlementineJBS to consider an edit to the Master List and report back: Generally we are not doing well at keeping track of who is making what. We need contributors to clarify their targets, and these should be included in the Master List as targets, where the "target" tag can be changed upon successful synthesis. Ideally to include a link to the URL where the molecule was suggested or discussed.

**Series 5 Benzimidazoles**

Oxazoles having good potencies in recent assays remain of high interest to the MycetOS project (as part of Series 5 development).

Remaining objectives on Series 5 

- [ ] @dosreic to try to obtain samples for testing.
- [ ] @memm0740 to search for whether additional samples could be obtained from other labs.
- [x] @AndreaOtago to clarify whether the https://github.com/OpenSourceMycetoma/series-5-benzimidazoles/issues/3#issuecomment-1556652617 has been shipped to @wwjvdsande.
- [ ] @fantasy121 to ask Sydney Hons students Peiyan to join Github and share ID.
- [ ] @memm0740 to update on progress of synthesis. Done https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/7#issuecomment-1622784020. @memm0740 to post link to raw data on ELN.

**Series 6 Ketoximes**
Third batch of molecules (**27 entries**) was dispatched to Rotterdam for testing.
Isomer interconversion experiments continue (heat, light,acid catalysis).

**Misc/AOB**
@MA-Jjingyi presented toxicity studies results from the latest compound screening performed at Erasmus MC

Molecules which have shown good performance and selected for further _in vivo_ evalutation (in late summer 2023) include:
- Series 2 Aminothiazoles (3 compounds)
- Series 5 Benzimidazoles (3 compounds)
- Natural products (4 compounds)
- MMV Global Health Priority Box (3 compounds)

In the _in vivo_ stage, most compounds will be tested against both _M.mycetomatis_ and _F.senegalensis_ strains.
 
[29082023.MyctOS.meeting.-MA.pptx](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12465327/29082023.MyctOS.meeting.-MA.pptx)

**Comment by AndreaOtago** [comment]
I likely won't join you live in August, however a very early answer to one of the agenda Qs - yes I shipped the 2023 CHEM 305 benzoxazole compounds to @wwjvdsande in May 2023, and I gave Mycetoma codes to all these compounds in the sheet before sending. We do OSN synthesis at Otago once a year in April-May, so you have all our new 2023 compounds :)

**Comment by MFernflower** [comment]
update on series 3 is here

https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6

@OpenSourceMycetoma/corecontrib

**Comment by JuliaSarju** [comment]
Hi everyone,

Update from the University of York Student Project. Our student group made
great progress and synthesized 10 series 2 compounds and obtained 3 crystal
XRD structures. They uploaded their data to the electronic notebook and
prepared a poster
<https://drive.google.com/file/d/11jWPCi1kvc6fg-Ur10j4ThAt3Rok90Xp/view?usp=sharing>
summarising their work. The compounds need further purification, we
probably don't have the capacity to purify them at the moment as we are
gearing up for delivering a new reformed course in September.  We all
really enjoyed working on this project!

We also plan to facilitate a group BSc project to run between September and
April (2 days a week) and would really like to continue contributing to the
Open Source Pharma Projects.
Are there particular areas it would be better for us to focus on for this
longer project?

I have trouble attending meetings on Tuesdays as I don't have childcare,
but I'll keep a close eye on the discussion threads.

Best wishes,
Julia
Dr Julia Sarju FHEA , [image: A button with "Hear my name" text for name
playback in email signature] <https://www.name-coach.com/julia-sarju>
She/Her
Lecturer in Chemistry, Year One Leader, and Chemistry Disability Contact
The University of York

*UG + PG Chemistry Students:* Do you have experiences of inequalities in
chemistry education that you want to share with chemistry instructors? Are
there actions you would like chemistry departments to take? Add your voice
and take part in this RSC Diversity and Inclusion project: Listening to
Inequalities in Chemistry Education
<https://docs.google.com/forms/d/e/1FAIpQLSfF-KSH-VXQOb55kLV_URwZkZVHB32QVM5TdapgSmEtJ3nTWQ/viewform?usp=sf_link>

Join the Student Disability Forum Mailing List
<https://docs.google.com/forms/d/e/1FAIpQLSejLDEYk84XxYXmFQmWphP0At3d0rjbIw_xrgVwS9hOAK7zRw/viewform>

**Comment by MFernflower** [comment]
@JuliaSarju perhaps if @mattodd doesnt have more pressing compounds you and
your students could take a stab at making some series 3 compounds? some
ideas are in here:


Message ID: <OpenSourceMycetoma/Monthly-zoom-meetings/issues/10/1651210888@
> github.com>
>

https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6

**Comment by JuliaSarju** [comment]
@MFernflower Those look really interesting!
Dr Julia Sarju FHEA , [image: A button with "Hear my name" text for name
playback in email signature] <https://www.name-coach.com/julia-sarju>
She/Her
Lecturer in Chemistry, Year One Leader, and Chemistry Disability Contact
The University of York

*UG + PG Chemistry Students:* Do you have experiences of inequalities in
chemistry education that you want to share with chemistry instructors? Are
there actions you would like chemistry departments to take? Add your voice
and take part in this RSC Diversity and Inclusion project: Listening to
Inequalities in Chemistry Education
<https://docs.google.com/forms/d/e/1FAIpQLSfF-KSH-VXQOb55kLV_URwZkZVHB32QVM5TdapgSmEtJ3nTWQ/viewform?usp=sf_link>

Join the Student Disability Forum Mailing List
<https://docs.google.com/forms/d/e/1FAIpQLSejLDEYk84XxYXmFQmWphP0At3d0rjbIw_xrgVwS9hOAK7zRw/viewform>

**Comment by MFernflower** [comment]
@mattodd @bebi78 I found an interesting compound library: https://www.opnme.com/ - Could not hurt for ask for samples? BI-3231 and crobenetine seem promising

**Comment by dmitrij176** [comment]
@mattodd @wwjvdsande @MA-Jjingyi @fantasy121 does anyone know what happened to the Master List online version.
All of the receent compound additions are missing. As if they have been deleted....

**Comment by MFernflower** [comment]
Strange - I just looked at the master list and it only now has fenarimols?!??! @OpenSourceMycetoma/corecontrib

**Comment by dmitrij176** [comment]
> Strange - I just looked at the master list and it only now has fenarimols?!??! @OpenSourceMycetoma/corecontrib

Someone must have accidentally deleted it.

**Comment by MFernflower** [comment]
I just forced a restore - hopefully all is well Dimitri @dmitrij176

**Comment by mattodd** [comment]
@OpenSourceMycetoma/corecontrib we need an informatics volunteer...

With respect to [the Epichem compounds that we hoped to obtain for the fenarimol series](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1530752314), I've managed to make contact with the Epichem team. It's not a simple situation, but for various reasons we have a narrow time window to request molecules. I sent the SCYX codes below to the relevant person, who is being exceptionally helpful, but it turns out it's not easy for them to find the molecules using these codes, and instead what's needed are DNDi or EPL-BS codes. Can someone please look at the codes below and provide the relevant other codes ASAP?

SCYX0001335912
SCYX0001322027
SCYX0001574838
SCYX0001338488
SCYX0001336037
SCYX0001388141
SCYX0001294212
SCYX0001278548
SCYX0001315839
SCYX0001255546
SCYX0001268121

**Comment by dosreic** [comment]
Codes below in blue


SCYX0001335912 EPL-BS0197

SCYX0001322027 EPL-BS0158
SCYX0001574838 EPL-BS0792
SCYX0001338488 EPL-BS0216
SCYX0001336037 EPL-BS0213
SCYX0001388141 EPL-BS0241
SCYX0001294212 EPL-BS0121
SCYX0001278548 EPL-BS0105
SCYX0001315839 EPL-BS0143
SCYX0001255546 EPL-BS0039
SCYX0001268121 EPL-BS0093

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 37 999072470 | ***@***.******@***.***>
dndi.org

[A picture containing text, clipart  Description automatically generated]

De: Mat Todd ***@***.***>
Enviada em: quinta-feira, 10 de agosto de 2023 06:52
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly Mycetoma Meeting 29th August 2023 (Issue #10)


@OpenSourceMycetoma/corecontrib<https://github.com/orgs/OpenSourceMycetoma/teams/corecontrib> we need an informatics volunteer...

With respect to the Epichem compounds that we hoped to obtain for the fenarimol series<https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1530752314>, I've managed to make contact with the Epichem team. It's not a simple situation, but for various reasons we have a narrow time window to request molecules. I sent the SCYX codes below to the relevant person, who is being exceptionally helpful, but it turns out it's not easy for them to find the molecules using these codes, and instead what's needed are DNDi or EPL-BS codes. Can someone please look at the codes below and provide the relevant other codes ASAP?

SCYX0001335912 EPL-BS0197

SCYX0001322027 EPL-BS0158
SCYX0001574838 EPL-BS0792
SCYX0001338488 EPL-BS0216
SCYX0001336037 EPL-BS0213
SCYX0001388141 EPL-BS0241
SCYX0001294212 EPL-BS0121
SCYX0001278548 EPL-BS0105
SCYX0001315839 EPL-BS0143
SCYX0001255546 EPL-BS0039
SCYX0001268121 EPL-BS0093

**Comment by mattodd** [comment]
Thank you so much @dosreic !

**Comment by MFernflower** [comment]
@wwjvdsande @bebi78 was the 4-ethyl-closamid and nitroxolin screened yet or are they on waiting list??

**Comment by MFernflower** [comment]
[@lferrins](https://github.com/lferrins) to perhaps post a list of compounds her group has in stock from previous projects about amoeba for possible re-use in mycetoma  

https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6

**Comment by JuliaSarju** [comment]
Hi everyone,

I would like to introduce my fab colleague, Dr Peter Rayner (@p-rayner). We will be working with year 3 BSc students who would like to carry out their final project contributing to this OSMycetoma Project. 

There is a lot of uncertainty about the number of students at the moment between 6 and 30. We were hoping to run 2-3 groups, where one group looks at the series 3 phenothiazines and the other group/s continues exploring the thiazoles (following on from the mini project students earlier in the year).

We really want these projects to be authentic and to contribute to the wider Mycetoma project. Any guidance and steering would be much appreciated. Unfortunately, neither of us can attend the August group meeting but we will look out for the minutes.

Best wishes,
Julia

**Comment by MFernflower** [comment]
A split between the aminothiazoles and the phenothiazines sounds like a
lovely idea as both series are easy to make and have unknown mechanisms of
actions

> Message ID: <OpenSourceMycetoma/Monthly-zoom-meetings/issues/10/1677388060
> @github.com>
>

@OpenSourceMycetoma/corecontrib

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib In my calender invite it was stated that the meeting would be on the 22nd of August. Here it is stated that it is the 29th. I asume it was shifted a bit because of the holidays. I will move the calender invite to match the date of the 29th.

**Comment by dmitrij176** [comment]
@wwjvdsande the bioassay shipment is ready for dispatch today.
Will there be anyone to collect it at Rotterdam tomorrow?

**Comment by wwjvdsande** [comment]
@dmitrij176 yes I will be in and @MA-Jjingyi too

**Comment by MA-Jjingyi** [comment]
Hi all, the updated results show in the slides, please check. 
[29082023 MyctOS meeting -MA.pptx](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12415984/29082023.MyctOS.meeting.-MA.pptx)

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib prof Sean doyle has shipped a fluorescent labled siderophore. Mickey Konings from our lab will test it out.

**Comment by dmitrij176** [comment]
> @dmitrij176 @fantasy121 is any of you currently working on the fenarimol manuscript? If not, can I do the ref check for the biological part of the manuscript. @mattodd noted that the references have shifted so I need to update that.

I have some remaining corrections to add. So does Hung I think.
But it should be fine as long as we all edit via Word synchronized with Dropbox.
Do you have this option @wwjvdsande?

**Comment by wwjvdsande** [comment]
@dmitrij176 @fantasy121 I'm using that now. I have created a new version called 28 august. I'm just checking the things which need to be done on our side and will replace the references with PMID numbers for now. The one who will submit will need to make an offline copy of it and has to add the references in a reference program such as endnote just before submission. I think that is why it went wrong. I used endnote but when the manuscript was transferred to dropbox the links were messed up.

**Comment by memm0740** [comment]
Hi All,
I won't be attending the meeting, so I have linked some slides which outline my synthesis progress. I am still trying to synthesise the lead compound in a relatively safe way. I believe I am close to achieving this.

[MycetOS 29th Aug meeting.pptx](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12462820/MycetOS.29th.Aug.meeting.pptx)

I have found a few groups in China and Russia that seem to have made the lead compound but was advised to not email them. I will continue looking into finding other groups that have made final compounds or intermediates.

Lastly Klementine and I are still working on entering all of the mycetoma compounds from @rohandavis. We are about half way.

**Comment by wwjvdsande** [comment]
@fantasy121 @mattodd @dmitrij176 for the paper: I added the missing values as calculated by @dosreic to the master file and the fixed supplementary database and reran the statistics. They are already included in the manuscript. The supplementary excell sheet is now also located in the dropbox.

**Comment by bebi78** [comment]
@OpenSourceMycetoma/corecontrib Dear all, I launched a new special issue about antifungals in IJMS (Q1 open access journal) with the topic "Antifungal Drug Discovery: Progresses, Challenges, Opportunities" (see link). 50% APC discounts are available, for eminent researchers full waivers can also be provided. Let me know if there is interest, submission deadline is end of February 2024. @dmitrij176 Maybe your ketoximes might become a suitable contribution?

https://www.mdpi.com/journal/ijms/special_issues/9QZD5S87RF

**Comment by bebi78** [comment]
@dmitrij176 Have you discussed a possible contribution to the special issue with @mattodd ?

**Comment by dmitrij176** [comment]
Good day Bernard. Mat was on holiday. Meeting him on Friday. Will let you know as soon as possible.

**Comment by bebi78** [comment]
Thanks @dmitrij176 . I talked to colleagues of the journal and I can provide a full waiver, 100% discount on APC, in case of paper acceptance (peer-review pending). Various very interesting scientists from Germany, France, USA and South America have already confirmed to contribute to this special issue.

**Comment by bebi78** [comment]
@mattodd @dmitrij176 @wwjvdsande Hello, I sent you the official invitations (one for Mat and one for Wendy) with the available 100% APC discounts for the mentioned antifungals special issue in IJMS.  I just have a request. I would need your proforma acceptance of my invitations for you, then I can reserve the full waivers for you. Just send me an email about it.

**Comment by dmitrij176** [comment]
Thank you Bernard.
Professor Todd(@mattodd) would you be so kind to send that email please.
Thank you in advance.
