### ISSUE TITLE
Monthly Mycetoma Meeting 26st September 2023

### ISSUE THREAD

**Issue by wwjvdsande** [OpenSourceMycetoma/Monthly-zoom-meetings#12]
Time: Sept 26th (12 noon UK, 1pm EU, 9pm Aus) [Timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=8&day=29&hour=11&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=152&p10=240).

The Outlook invite can be found [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/files/9674081/Monthly.MycetOS.meeting00.zip)

Location: https://uni-sydney.zoom.us/j/99281549497. In case of failure, use https://ucl.zoom.us/j/99789829423 and in case of double failure use [MycetOS meeting teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2I2MDcxZTgtYjZjOS00YTdmLTgwZTMtNWQ3OTc4NDY0MDNj%40thread.v2/0?context=%7b%22Tid%22%3a%22526638ba-6af3-4b0f-a532-a1a511f4ac80%22%2c%22Oid%22%3a%22a5ed84b8-5af1-42c6-9f8d-240f23a5d997%22%7d)
Chair: ErasmusMC
Minute taker: USyd
Previous meeting: (https://youtu.be/wzbRzA6anBQ)
Recording: [here](https://youtu.be/wzbRzA6anBQ)
Present:
Apologies: @fantasy121 @MA-Jjingyi 

**AGENDA**

### Series 1 - Fenarimols

_Final Molecules/SAR Gaps_

[@fantasy121 completed the selection of Epichem molecules](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1530752314), and the next step is to get them to Wendy.

- [ ] @mattodd is in touch with Epichem (Martine was on vacation) and will email the finalised list to them. TO BE UPDATED:

@fantasy121 shared [the list of compounds that have been shipped from Sydney to ErasmusMC](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1542026215). 

- [x] @MA-Jjingyi to evaluate these latest fenarimols and post data to the Master List, though there is a delay because of a problem at the production site for larvae. TO BE UPDATED:

- [ ] @meh-cyprian to proceed to try to model fenarimol compounds in potential protein target [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/68#issuecomment-1546869698), or to clarify what more data are needed. Aim is to better understand the SAR via docking vs homology model of protein. TO BE UPDATED: 

_Paper:_

- [ ] @dmitrij176 to upload offline copy of fenarimol lab notebook to UCL respository and provide link (@fantasy121 is https://doi.org/10.25910/CS81-G976). @mattodd to assist with copying data over.
- [x] @MA-Jjingyi @wwjvdsande generate an offline excel sheet with all the fenarimol screening data. 
- [x] @dosreic add the final logD data to the master table, entries were sent via e-mail by @wwjvdsande to make the entry in the software easier
- [ ] @dmitrij176 @fantasy121 @mattodd check supplementary table made by @wwjvdsande 
- [x] @wwjvdsande corrected figures and references in the manuscript
- [x] @dmitrij176 to make corrections to manuscript.
- [ ] @fantasy121 to make corrections to manuscript.
- [ ] References need to be sorted after final manuscript review. There is a recurring compatibility issue when editing via Dropbox. 

Currently there is a mismatch in numbers of analogues between the SI excel file and the the manuscript.

MYOS codes to be used for the compounds, to maintain the link between compounds in the paper and compounds in the live project. The codes needed are just the initial integers, not the batch/salt codes etc. Can also remove zeroes for readability, so e.g. MYOS7.

_Siderophores:_

New transcriptomic data from @wwjvdsande in the galleria grain model showed that siderophores are produced (https://github.com/OpenSourceMycetoma/What-other-molecules-to-screen/issues/10). These siderophores might be used as a trojan horse to get molecules into the grain. Could we couple fenarimols to fungal-relevant siderophores may be to get them in? The idea of the siderophores was of interest and all partners agreed to consider whether this could be done at the different sites. There is also potential relevance to other series. 

- [ ] @OpenSourceMycetoma/corecontrib to report back on potential structures (in the original issue https://github.com/OpenSourceMycetoma/What-other-molecules-to-screen/issues/10) and ways they might be produced within the resources available. This may be made obsolete by:
- [x] @wwjvdsande to pursue a link with Prof Doyle in Ireland who might be able to attach a fluorophore to a siderophore that would permit assessment of whether the siderophore transported the fluorophore into the grain. TO BE UPDATED: 

### Series 2 - Aminothiazoles

@KlementineJBS is the corresponding researcher for this project at USyd. @KlementineJBS has updated the [Wiki](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/All-Compounds-Made-To-Date) with the compounds successfully synthesised by USyd in June.

Molecules made by UCL MSc cohort (**23 entries**) have been shipped to Erasmus MC for testing. Same applies for selected Whitgift compound (MYOS_0590_00_01).

- [ ] Are all these compounds now in the Master List?

UCL Masters student cohort began in late May and has now (late July) finished their synthetic work.

- [ ] @mattodd to organise next meeting of the wider group: taking place THURS SEPT 28th 10 a.m. London time. Link/issue? Is everyone invited?
- [ ] @AndyBishopSevenoaks @JuliaSarju are there any samples likely to be incoming?
- [ ] @dosreic to try to secure samples related to this paper https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11 ?
- [ ] @KlementineJBS to consider an edit to the Master List and report back: Generally we are not doing well at keeping track of who is making what. We need contributors to clarify their targets, and these should be included in the Master List as targets, where the "target" tag can be changed upon successful synthesis. Ideally to include a link to the URL where the molecule was suggested or discussed.

### Series 5 - Benzimidazoles

The related oxazoles:
Good potencies observed for recent compound batches (e.g. [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/82#issuecomment-1325150305)). These resemble the benzimidazoles which have shown potent in vivo efficacy. Some oxazoles will be tested against _Falciformispora senegalensis_ too. This series will be evaluated _in vivo_ in the new larval season.

- [ ] @dosreic to try to obtain samples.
- [ ] @memm0740 to search for whether additional samples could be obtained from other labs.
- [x] @AndreaOtago to clarify whether the [new set of benzoxazoles](https://github.com/OpenSourceMycetoma/series-5-benzimidazoles/issues/3#issuecomment-1556652617) has been shipped to @wwjvdsande.
- [ ]  @fantasy121 to ask Sydney Hons students Peiyan to join Github and share ID.
- [ ] @memm0740 to update on progress of synthesis. Done [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/7#issuecomment-1622784020). Can this be added to the wiki, so we can close this action item?
- [ ] @memm0740 to post link to raw data on ELN.

### Series 6: ketoximes

Latest compound shipment [here](https://github.com/OpenSourceMycetoma/Series-6-Ketoximes/issues/5), to be tested by @MA-Jjingyi. TO BE UPDATED

@bebi78 suggested evaluating different salts of the ketoximes.

### Series 3: Tricyclics/Phenothiazines

- [x] @wwjvdsande and @lferrins to arrange for shipment of compounds - issue page here: https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6
- [ ] @JuliaSarju and team to give update on phenothiazine synthesis projects - see https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/8

### Misc updates:

DMPK measurements by Dundee. Compound selection took place in #8. No updates yet.

Compounds are being shipped from NEU to Erasmus MC: https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6#issuecomment-1716760729

MMV Global Health Priority Box screened against _Madurella mycetomatis_ and _Falciformispora senegalensis_. Led to the identification of promising hits [MMV1593278, MMV1804559 and MMV020335](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/6#issuecomment-1567312472).

- [x] @MA-Jjingyi to evaluate these compounds in the _in vivo_ model.

- [ ] @memm0740 to enter the data for [Rohan Davies' compounds](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/84#issuecomment-1507518700) into the Master List. They need [MyOS codes](https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/The-Molecule-Numbering-Convention).

Kinase inhibitor library. The updated KCGS library was ordered on 1st of May. It has arrived in Erasmus MC. Bio-informatical analyses have been carried out by Mickey. @bebi78 can send some 10 targets. Mickey screened this last week for the first time, repeat is scheduled for this week.

- [ ] Data from KCGS to be reported.

Bioinformatics: Waleed requested information on which aspect of bioinformatics should be prioritised to work on first. @wwjvdsande corresponded offline with him. This will include a Phylogenetic tree to work out relationships of various species were identified as high priorities so that we can search the literature for closely related species to Mycetoma, and for the potential structures of the drug target, which would enable us to simulate our data/estimation/computational models. In the May meeting @TariqAyub attended from the Qasim group who will advise on what can be done in terms of future contributions. TO BE UPDATED

In the last meeting @MA-Jjingyi presented toxicity studies results from the latest compound screening performed at Erasmus MC

- [ ] Where are the data, and are there any key messages?

Molecules which have shown good performance and selected for further _in vivo_ evalutation (in late summer 2023) include:
- Series 2 Aminothiazoles (3 compounds)
- Series 5 Benzimidazoles (3 compounds)
- Natural products (4 compounds)
- MMV Global Health Priority Box (3 compounds)

In the _in vivo_ stage, most compounds will be tested against both _M.mycetomatis_ and _F.senegalensis_ strains.

### Next Meeting

 October <strike>24</strike> 31 2023: chair: UCL; minute taker: ErasmusMC

**Comment by MA-Jjingyi** [comment]
[26092023 MyctOS meeting -MA.pptx](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12684110/26092023.MyctOS.meeting.-MA.pptx)
Hi all, the update of in vivo data shows in this slide. please check.  please leave messages if you have any question. 
by the way, due to my holiday, I would not attend September and October monthly meeting.

**Comment by fantasy121** [comment]
Hi all, I'll be an apology for tonight.

Just a brief update from me. I am half way through updating the manuscript and aim to complete this by end of this week.

**Comment by mattodd** [comment]
For those joining late, we're in the UCL meeting link.

**Comment by KlementineJBS** [comment]
I'll pop some minutes up later this week when I've had a chance to edit them into something more coherent. 

For now, just a link to the [issue](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/17) with the Schools meeting on Thursday and a reminder of the details: 

Time: Sep 28, 2023 07:00 PM Sydney (10:00 AM London)

Meeting ID: 852 2722 1625

https://uni-sydney.zoom.us/j/85227221625

**Comment by MFernflower** [comment]
@KlementineJBS I don't think I will be there for breaking good meeting but I had messaged @JuliaSarju about possibly having a one or two students from the school groups to make the pair of S3 phenothiazines I think that would complement the NEU tricyclic library well

**Comment by MFernflower** [comment]
(repost because I didn't have the image of the structures and I messed up the previous post) 

@KlementineJBS I don't think I will be there for breaking good meeting but I had messaged @JuliaSarju about possibly having a one or two students from the school groups to make the pair of S3 phenothiazines that I think that would complement the NEU tricyclic library well


![phenothiazine_pair](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/assets/3164942/df2644f7-b161-4e96-b23f-ef2e3d2cbb7e)

**Comment by dmitrij176** [comment]
@wwjvdsande further to our conversation during last MycetOS meeting, is there any buffer solution that you would recommend for ketoxime stability testing?
Experiment objective is to model buffer environment used for in vitro tests.
Maybe few common buffers which are the golden standard for these assays?

**Comment by MFernflower** [comment]
Phosphate buffered saline is a common one in biochemistry  @dmitrij176

**Comment by dmitrij176** [comment]
> Phosphate buffered saline is a common one in biochemistry  @dmitrij176
> 
> > Message ID: <OpenSourceMycetoma/Monthly-zoom-meetings/issues/12/1742181149
> > @github.com>
> >
> 

I know. But it's not the one used for MycetOS in vitro assays...

**Comment by KlementineJBS** [comment]
# Minutes 

_Please make edit any inaccuracies - and apologies for any misspelled names!_

As a document: 
[Mycetoma meeting minutes 26-09-23.docx](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12799347/Mycetoma.meeting.minutes.26-09-23.docx)

Relevant files:
[26092023 MyctOS meeting -MA.pptx](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12684110/26092023.MyctOS.meeting.-MA.pptx)

Chair: ErasmusMC
Minute taker: USyd
Previous meeting: (https://youtu.be/wzbRzA6anBQ)
Recording: [here](https://youtu.be/wzbRzA6anBQ)
Present: @mattodd @MFernflower @wwjvdsande @dmitrij176 @KlementineJBS, Lori Ferrins, Marai, Bernhard
Apologies: @fantasy121 @MA-Jjingyi
 
## Results of larvae testing – presented by Wendy

Desired results are low toxicity to larvae and increased survival (i.e. prolonged survival of larvqe). 
Have be able to test:
•	3 compounds of Series 2:  Aminothiazoles (MYOS421, MYOS425, MYOS426)
•	3 compounds of Series 5:  benzimidazoles (MYOS326, MYOS333, MYOS334)
•	4 compounds of Nature Products (MYOS456 – MYOS459)
•	3 compounds of MMV Global Health Priority Box (MMV14593278, MMV020335, MMV1804559)

Series 2 compounds were not toxic to larvae but did not prolong larvae survival.

Series 3 compounds were toxic to larvae at a 20 uM dose but not at a 10 uM dose. MYOS333 and MYOS334 prolonged larvae survival (p=0.0487 and p=0.0431 respectively). None of them prolonged survival in F. s

Nature Products compounds were not toxic to larvae but did not prolong larvae survival.

MMV1804559 was toxic in larvae at 20µM, but not at 10µM. MMV1804559 prolonged MM55-infected larvae survival (P = 0.0313). Combination treatment of MMV1804559 and ITZ prolonged MM55-infected larvae survival (P = 0.0465).

### Discussion

-	Best prolonged survival so far was from a benzimidazole and was not over 50%. Log rank is used to test survival across different time periods. Sometimes, drugs will prolong survival for the first four days (while it’s still present in the system) but not over the full 10 days. It’s still possible to see significant results after a shorter period of just four days.
-	Testing of toxicity at different concentrations is limited by resources/number of compounds that require testing
-	Can only use small amounts of DMSO before the DMSO itself starts to affect the larvae. 
-	Aquadest is used as a negative control and amphotericin B as a positive control (not itraconazole, ITZ). This is because ITZ doesn’t actually prolong survival – it facilitates encapsulation of lesions and makes them easier to remove via surgery, but does not kill the fungus. Amphotericin B does prolong survival but is not used as a standard drug for treating mycetoma as needs to be used for a full year. 
-	In these tests, the experiment is considered not valid if any of the following occur: infected control doesn’t have a normal survival curve, amphotericin B does not significantly prolong survival, aquadest control survives. Amphotericin B treated samples should always have a higher/different survival rate. 
-	Model is appropriate because it reflects the mammalian system. It is a “tough” model – not a lot of compounds pass – because of the need for compounds to penetrate the biofilm.
-	We are hopeful that benzimidazoles will be able to penetrate the biofilm. 
-	Have considered co-administration biofilm disruptors, but it seems that these need to be coupled to the drug itself as they must pass through the same channel as the drug itself. This has been shown to be possible with dyes. 
-	Possible research project: coupling siderophores to antifungals – fungus needs iron to live so maybe this would be a “magic bullet” solution. Unfortunately, in vivo testing is require to assess penetration of biofilm. 

## Series 1 fenarimols. 

No update on protein modelling – the people involved have not made contact. 

Almost all issues have been resolved with the paper except references. It’s currently with Hung but Dmitrij will email him to get an update.

## Siderophores.

It’s possible that that compounds with good in vitro performance will not work in vivo. Wendy has been in contact with Sean Doyle, who has a fluorescent labelled siderophore. This will be tested in the last few weeks of larvae season. 

Wendy’s new intern, Marai, will be testing compounds for a few months, untilthe end of January.

### Discussion 

-	Wendy’s team has had an issue with double-ups in the MYOS codes. Dmitrij has resolved these double-ups and will email Wendy to clarify. 
-	About 129 compounds are waiting for in vitro testing, with about 44 more compounds due to arrive soon. Lots of testing will be done during winter while Marai is here, but testing will continue until summer.
-	Questions about the buffer used in testing – only DMSO diluted with water is used. Fungus is in RPMI, a typical cell media. Cells are cultured for over a week and are only in contact with viability dye for max. 5 hours.
-	Ma will be in the final stages of her PhD next year, which might make screening difficult as it takes time to develop the required skills. Larvae season falls during summer holidays which makes it difficult to get interns.

## Series 3.

Mickey is screening kinase inhibitors. Has had to use a higher concentration for some of them to identify hits. Results are mostly disappointing.

Never heard back from Waleed about bioinformatics.

### Discussion

-	Can toxicity data be included in the master list spreadsheet?
-	Is there currently a good way to share existing ADME, tox results etc for new compounds? Currently, we only collect data on larvae toxicity. However, Lori Ferrins has a lot of data on compounds already, but not insect toxicity. 
-	Any results on insect toxicity can be shared with Lori 
-	Mat suggests pasting excel file into the master list and generating MYOS codes from there
-	Bernhard is editing a special issue about antifungal drugs and drug development for the International Journal of Molecular Sciences (MDPI, 5.6 IF, open access). He has two full fee waivers to offer and wants to know if we are interested. Deadline is end of Feb, but if we suggest a paper and it doesn’t work out by January we can withdraw. 
-	This might be a good home for the ketoxime paper, not sure about the fenarimols paper. 
-	Bernhard needs suggested titles to send out invites. 
-	Note that anything below 20% growth is considered inhibition and anything > 20% growth is considered growth (i.e. not a good result).

**Comment by dosreic** [comment]
Hi everyone, yes, I have just confirmed, we can ship these 5 compounds from TCG to Wendy.
How much should we send? And Wendy, can you confirm your address and if I can proceed with it?

Best wishes,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 37 999072470 | ***@***.******@***.***>
dndi.org

[A picture containing text, clipart  Description automatically generated]

De: Mat Todd ***@***.***>
Enviada em: terça-feira, 3 de outubro de 2023 10:27
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly Mycetoma Meeting 26st September 2023 (Issue #12)


Epichem compound update, with respect to last correspondence on this at #10 (comment)<https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/10#issuecomment-1672913606>

Jason Chaplin at Epichem has very kindly communicated (to Mat by email) the status of the various compounds below. The complication here is that Epichem is in a period of transition, so finding and shipping compounds will be a big challenge. He's hoping that for the TCGLS compounds below @dosreic<https://github.com/dosreic> or Eric Chatelain from DNDi might be able to chase. He will monitor the situation for the handful of Epichem compounds in case he can secure the samples and ship. I'll maintain contact. He also suggested a bit of QC, given that the samples are 10 years old, though they apparently "still look like nice powders though".

Maintain this action on @mattodd<https://github.com/mattodd> re final SAR gap shipment.

SCYX0001335912 EPL-BS0197 Shipped to TCG for DNDi
SCYX0001322027 EPL-BS0158 Vial not found likely in other boxes requiring further investigation
SCYX0001574838 EPL-BS0792 Shipped to TCG for DNDi
SCYX0001338488 EPL-BS0216 Shipped to TCG for DNDi
SCYX0001336037 EPL-BS0213 Shipped to TCG for DNDi
SCYX0001388141 EPL-BS0241 Shipped to TCG for DNDi
SCYX0001294212 EPL-BS0121 Sample at Epichem
SCYX0001278548 EPL-BS0105 Sample at Epichem
SCYX0001315839 EPL-BS0143 Sample at Epichem
SCYX0001255546 EPL-BS0039 Sample at Epichem
SCYX0001268121 EPL-BS0093 Sample consumed No stock remaining

**Comment by MFernflower** [comment]
@dosreic 5 to 10 milligrams of product can be sent

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib the next MycetOS meeting is scheduled next week. ErasmusMC is minute taker. However both Ma and I are abroad and not able to join. Can either some-one else be minute taker or can we move it to 31 oktober?

**Comment by KlementineJBS** [comment]
> @OpenSourceMycetoma/corecontrib the next MycetOS meeting is scheduled next week. ErasmusMC is minute taker. However both Ma and I are abroad and not able to join. Can either some-one else be minute taker or can we move it to 31 oktober?

I'm happy to take minutes, but if you and/or Ma would prefer to move it to the 31st that's fine by me too.

**Comment by mattodd** [comment]
I vote move to Oct 31st - slightly better for me too.

**Comment by bebi78** [comment]
Oct 31 also OK for me.

**Comment by dosreic** [comment]
Hi everyone, just want to follow up on this. I need the quantity and address to send the compounds to Wendy.

Cheers,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 37 999072470 | ***@***.******@***.***>
dndi.org

[A picture containing text, clipart  Description automatically generated]

De: Luiza Cruz
Enviada em: quarta-feira, 4 de outubro de 2023 12:16
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>; OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Mention ***@***.***>
Assunto: RES: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly Mycetoma Meeting 26st September 2023 (Issue #12)

Hi everyone, yes, I have just confirmed, we can ship these 5 compounds from TCG to Wendy.
How much should we send? And Wendy, can you confirm your address and if I can proceed with it?

Best wishes,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 37 999072470 | ***@***.******@***.***>
dndi.org

[A picture containing text, clipart  Description automatically generated]

De: Mat Todd ***@***.******@***.***>>
Enviada em: terça-feira, 3 de outubro de 2023 10:27
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.******@***.***>>
Cc: Luiza Cruz ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly Mycetoma Meeting 26st September 2023 (Issue #12)


Epichem compound update, with respect to last correspondence on this at #10 (comment)<https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/10#issuecomment-1672913606>

Jason Chaplin at Epichem has very kindly communicated (to Mat by email) the status of the various compounds below. The complication here is that Epichem is in a period of transition, so finding and shipping compounds will be a big challenge. He's hoping that for the TCGLS compounds below @dosreic<https://github.com/dosreic> or Eric Chatelain from DNDi might be able to chase. He will monitor the situation for the handful of Epichem compounds in case he can secure the samples and ship. I'll maintain contact. He also suggested a bit of QC, given that the samples are 10 years old, though they apparently "still look like nice powders though".

Maintain this action on @mattodd<https://github.com/mattodd> re final SAR gap shipment.

SCYX0001335912 EPL-BS0197 Shipped to TCG for DNDi
SCYX0001322027 EPL-BS0158 Vial not found likely in other boxes requiring further investigation
SCYX0001574838 EPL-BS0792 Shipped to TCG for DNDi
SCYX0001338488 EPL-BS0216 Shipped to TCG for DNDi
SCYX0001336037 EPL-BS0213 Shipped to TCG for DNDi
SCYX0001388141 EPL-BS0241 Shipped to TCG for DNDi
SCYX0001294212 EPL-BS0121 Sample at Epichem
SCYX0001278548 EPL-BS0105 Sample at Epichem
SCYX0001315839 EPL-BS0143 Sample at Epichem
SCYX0001255546 EPL-BS0039 Sample at Epichem
SCYX0001268121 EPL-BS0093 Sample consumed No stock remaining

**Comment by wwjvdsande** [comment]
@dosreic we usually need 1-2 mg for the initialen in vitro screenings. For the larvae work 5 mg is recommended

**Comment by dosreic** [comment]
Ok, some of these compounds we don’t have a lot of quantity, but I will send everything to you. Can you please confirm your address and contact details?

Best,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 37 999072470 | ***@***.******@***.***>
dndi.org

[A picture containing text, clipart  Description automatically generated]

De: Wendy van de Sande ***@***.***>
Enviada em: quinta-feira, 26 de outubro de 2023 08:13
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly Mycetoma Meeting 26st September 2023 (Issue #12)


@dosreic<https://github.com/dosreic> we usually need 1-2 mg for the initialen in vitro screenings. For the larvae work 5 mg is recommended

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib we screened these:
SCYX0001335912 EPL-BS0197 Shipped to TCG for DNDi --> not inhibited at 100 uM
SCYX0001574838 EPL-BS0792 Shipped to TCG for DNDi --> not inhibited at 100 uM
SCYX0001338488 EPL-BS0216 Shipped to TCG for DNDi  --> inhibited at 100 and 25 uM
SCYX0001336037 EPL-BS0213 Shipped to TCG for DNDi --> inhibited at 100 and 25 uM
SCYX0001388141 EPL-BS0241 Shipped to TCG for DNDi --> inhibited at 100 and 25 uM

But I don't think they are in the spreadsheet with MYOS-codes, Can somebody get them codes?
