### ISSUE TITLE
Monthly Mycetoma Meeting 31 october 2023

### ISSUE THREAD

**Issue by wwjvdsande** [OpenSourceMycetoma/Monthly-zoom-meetings#13]
Time: Oct 31st (12 noon UK, 1pm EU, 9pm Aus, 8am EDT) 

The Outlook invite can be found [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/files/9674081/Monthly.MycetOS.meeting00.zip)

Location: https://uni-sydney.zoom.us/j/99281549497. In case of failure, use https://ucl.zoom.us/j/99789829423 and in case of double failure use [MycetOS meeting teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2I2MDcxZTgtYjZjOS00YTdmLTgwZTMtNWQ3OTc4NDY0MDNj%40thread.v2/0?context=%7b%22Tid%22%3a%22526638ba-6af3-4b0f-a532-a1a511f4ac80%22%2c%22Oid%22%3a%22a5ed84b8-5af1-42c6-9f8d-240f23a5d997%22%7d)
Chair: UCL
Minute taker: ErasmusMC 
Previous meeting: [here](https://youtu.be/wzbRzA6anBQ)
Recording: 
Present: @mattodd @dmitrij176 @fantasy121 @bebi78 @wwjvdsande @MA-Jjingyi @Marij @MFernflower @eloizidou @marij
Apologies: @KlementineJBS 

AGENDA and MINUTES
**MycetOS won the open science award of Erasmus University**
Erasmus University was awarding open science projects in which the university was involved. From the 31 projects which were submitted, MycetOS was given the award. Congratulations to all!
https://github.com/OpenSourceMycetoma/Talks-Meetings-Publicity/issues/4

****In vitro** screening**

- [x] With the larvae season comming to an end we now started with screening the new molecules. We have screened a high and low dosage of half of the compounds and will upload the data upcomming week. 

**Series 1 - Fenarimols**
- [x] Final Molecules/SAR Gaps. https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1530752314. @mattodd is in touch with Epichem (Justin Chaplin) and has emailed the final list to them. They have responded and @dosreic has looked into having some shipped from TLGLS to Wendy. Current status is [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/12#issuecomment-1744978511) --> 5 were shipped and 4 were available.
- [ ] From the synthesized compounds (which?) several have been screened. MYOS00510 and MYOS00518 were hits.
[ ] @meh-cyprian to proceed to try to model fenarimol compounds in potential protein target https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/68#issuecomment-1546869698, or to clarify what more data are needed. Aim is to better understand the SAR via docking vs homology model of protein. --> no news yet. We need to contact them one more time. @mattodd will do.
- [ ] Paper: is the paper ready for everyone to read it one more time and then submit?  --> version 3 oct was the latest version in dropbox. Hung updated the writing. What is still needed are the concluding remarks. So what is known on CYP51. Do our results link to data what is known on Cyp51? May be look at the azoles. So do @dmitrij176 or @fantasy121 already have this in the discussion of their thesis. If so can this be added to the paper.  Also the coding of the compounds needs addressing. We were using MYOS codes as numbering. This is also useful for those who want to look them up in the MycetOS spreadsheet. However the intermediate ones are currently numbered as Int#. Conclusion lets use Int for the intermediate ones. 

**Siderophores:**
Fluoroscent siderophore was tested in the larvae in the last weeks of the season.

- [ ] The results need to be processed. --> need to correct for autofluorescence

**Series 2 - Aminothiazoles**
@KlementineJBS is the corresponding researcher for this project at USyd. @KlementineJBS has updated the [Wiki](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/All-Compounds-Made-To-Date) with the compounds successfully synthesised by USyd in June.
- [ ] Update from @KlementineJBS from the [schools meeting](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/17)? --> discussion was on which molecules where going to be made next.

Molecules made by UCL MSc cohort (23 entries) have been shipped to Erasmus MC for testing. Same applies for selected Whitgift compound (MYOS_0590_00_01). The compounds were diluted and a first screening was performed. The results will be uploaded this week on the spreadsheet. 

**MYOS-codes**. The team at ErasmusMC lost a lot of time figuring out which compounds where which due to the renumbering of compounds and the duplication of numbers. Please, before shipping any compounds make sure that the MYOS codes are already in the spreadsheet and correct. Problem now was that compounds were sent before they were entered in the spreadsheet and therefore the same codes where used by others too. This is confusing and prone to mistakes! The numbering convention is at https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/The-Molecule-Numbering-Convention -->  the renumbering was also done on the vial itself to avoid problems in the future when compounds need to be rescreened. For numbering. On (https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki) it is explained on how to do this.

**Series 5 - Benzimidazoles**
The related oxazoles: testing is ongoing. So far MYOS00527 was the only hit. Results to be uploaded.

**Series 6: ketoximes**
Latest compound shipment https://github.com/OpenSourceMycetoma/Series-6-Ketoximes/issues/5, to be tested by @MA-Jjingyi. Marij screened the first barch. So far we have 5 hits for which the IC50 will be determined. Results to be uploaded

**Series 3: Tricyclics/Phenothiazines**
- [ ] https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6 - Data has been uploaded to separate sheet in the masterlist  - can soembody with better spreadsheet skills than I  (@MFernflower ) have merge it with the main sheet and give the compounds myos codes?

- [ ] @JuliaSarju and team to give update on phenothiazine synthesis projects - see https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/8

**Kinase inhibitor library.** 
The KCGS library was screened by Mickey. Additional drugs of similar classes were sent by @bebi78  and screened by Marij. In total 6 drugs from the KCGS appeared to be hits along with one from the package sent by @bebi78. 

**Bioinformatics**
- [x] Did anyone hear from Waleed? @wwjvdsande  to check if he is still interested. To clarify means of contact in the meeting.

**Misc updates**:
- [ ] DMPK measurements by Dundee. Compound selection took place in https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/8. Are there any updates?. @mattodd will this further

**Next Meeting**
November 27, 2023: chair: USyd; minute taker: UCL

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib i'm currently in ghana. I will make the agenda as soon as possible after my return. Face some issues with the internet here

**Comment by wwjvdsande** [comment]
https://github.com/OpenSourceMycetoma/Talks-Meetings-Publicity/issues/4#issue-1963207090

**Comment by bebi78** [comment]
@OpenSourceMycetoma/corecontrib For those members outside Europe, keep in mind that Europe returns to standard time tonight again. Just to ensure that you don't miss the meeting on Tuesday.

**Comment by MFernflower** [comment]
Will this be Oct 31 8 am EDT? @Mattodd

**Comment by KlementineJBS** [comment]
I'm afraid I won't be able to make it to this meeting as it's very late here in Australia and I'm not too well. 

I did just want to mention that I've been experimenting with new ways to share our work on the 2-aminothiazoles and have written up a guide on the [Wiki](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki) on how to share compounds in a way that will hopefully prevent duplication of both compounds themselves and MYOS codes - if anyone has suggestions please let me know. 

I've also posted some compounds we're planning to make [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/19), but we probably won't be focussing on these until the new year.

**Comment by wwjvdsande** [comment]
@KlementineJBS may be we should discuss if we can create alternating meeting schedules so that it will be easier for you to join as well (even if it is only half of the time). I will raise this in the meeting.

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib we are currently using the sydney zoom link

**Comment by wwjvdsande** [comment]
Proposed timings:
- even month: New York 8:00, London 12:00, Europe 13:00, Sydney 23:00 (european wintertime) and  New York 7:00, London 12:00, Europe 13:00, Sydney 21:00 (european summertime)

Any of these options? Please let us know the preference by putting your name behind it using the Edit button:
- odd month: 
- A: New York 8:00, London 12:00, Europe 13:00, Sydney 23:00 (european wintertime) and  New York 7:00, London 12:00, Europe 13:00, Sydney 21:00 (european summertime)
- B: New York 6:00, London 10:00, Europe 11:00, Sydney 21:00 (european wintertime) and New York 5:00, London 10:00, Europe 11:00, Sydney 19:00 (european summertime)
- C: New York 4:00, London 8:00, Europe 9:00, Sydney 19:00 (european wintertime) and New York 3:00, London 8:00, Europe 9:00, Sydney 17:00 (european summertime)
- D: New York 16:30, London 20:30, Europe 21:30, Sydney 07:30 (european wintertime) and New York 15:30, London 20:30, Europe 21:30, Sydney 5:30 (european summertime)

**Comment by AndreaOtago** [comment]
> @KlementineJBS may be we should discuss if we can create alternating meeting schedules so that it will be easier for you to join as well (even if it is only half of the time). I will raise this in the meeting.

I would be keen to join in some meetings as well if some were at better times, New Zealand is 2-3 hours ahead of Australian times so I haven't been coming to 1am meetings :) I'll write my name by some preferences

**Comment by wwjvdsande** [comment]
@OpenSourceMycetoma/corecontrib we uploaded the initial screening data for the compounds screened so far. Also the epichem compounds arrived today.

**Comment by animarfavi** [comment]
> Proposed timings:
> 
> * even month: New York 8:00, London 12:00, Europe 13:00, Sydney 23:00 (european wintertime) and  New York 7:00, London 12:00, Europe 13:00, Sydney 21:00 (european summertime)
> 
> Any of these options? Please let us know the preference by putting your name behind it using the Edit button:
> 
> * odd month:
> * A: New York 8:00, London 12:00, Europe 13:00, Sydney 23:00 (european wintertime) and  New York 7:00, London 12:00, Europe 13:00, Sydney 21:00 (european summertime)
> * B: New York 6:00, London 10:00, Europe 11:00, Sydney 21:00 (european wintertime) and New York 5:00, London 10:00, Europe 11:00, Sydney 19:00 (european summertime). ANDREA/NZ MAYBE. KLEMENTINE YES.
> * C: New York 4:00, London 8:00, Europe 9:00, Sydney 19:00 (european wintertime) and New York 3:00, London 8:00, Europe 9:00, Sydney 17:00 (european summertime). ANDREA/NZ YES. KLEMENTINE YES.
> * D: New York 16:30, London 20:30, Europe 21:30, Sydney 07:30 (european wintertime) and New York 15:30, London 20:30, Europe 21:30, Sydney 5:30 (european summertime). ANDREA/NZ YES. KLEMENTINE YES.

Hi team, I can't edit this post, but I'm happy with options B, C and D.

**Comment by dosreic** [comment]
Hi everyone,

For me, anything past 12pm GMT works for me (even month ok, odd month options A and D)

Cheers,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 37 999072470 | ***@***.******@***.***>
dndi.org

[A picture containing text, clipart  Description automatically generated]

De: animarfavi ***@***.***>
Enviada em: quinta-feira, 16 de novembro de 2023 00:24
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly Mycetoma Meeting 31 october 2023 (Issue #13)


Proposed timings:

  *   even month: New York 8:00, London 12:00, Europe 13:00, Sydney 23:00 (european wintertime) and New York 7:00, London 12:00, Europe 13:00, Sydney 21:00 (european summertime)

Any of these options? Please let us know the preference by putting your name behind it using the Edit button:

  *   odd month:
  *   A: New York 8:00, London 12:00, Europe 13:00, Sydney 23:00 (european wintertime) and New York 7:00, London 12:00, Europe 13:00, Sydney 21:00 (european summertime)
  *   B: New York 6:00, London 10:00, Europe 11:00, Sydney 21:00 (european wintertime) and New York 5:00, London 10:00, Europe 11:00, Sydney 19:00 (european summertime). ANDREA/NZ MAYBE. KLEMENTINE YES.
  *   C: New York 4:00, London 8:00, Europe 9:00, Sydney 19:00 (european wintertime) and New York 3:00, London 8:00, Europe 9:00, Sydney 17:00 (european summertime). ANDREA/NZ YES. KLEMENTINE YES.
  *   D: New York 16:30, London 20:30, Europe 21:30, Sydney 07:30 (european wintertime) and New York 15:30, London 20:30, Europe 21:30, Sydney 5:30 (european summertime). ANDREA/NZ YES. KLEMENTINE YES.

Hi team, I can't edit this post, but I'm happy with options B, C and D.

**Comment by mattodd** [comment]
Closing since all actions taken on to next meeting and all comments folded in.
