### ISSUE TITLE
 Monthly Mycetoma Meeting 27 February 2024

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Monthly-zoom-meetings#17]
Time: Feb 27th (12 noon UK) [Timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=2&day=27&hour=12&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240).

The Outlook invite can be found [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/2#issuecomment-1905476888)

Location: https://uni-sydney.zoom.us/j/99281549497. In case of failure, use https://ucl.zoom.us/j/99789829423 and in case of double failure use [MycetOS meeting teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2I2MDcxZTgtYjZjOS00YTdmLTgwZTMtNWQ3OTc4NDY0MDNj%40thread.v2/0?context=%7b%22Tid%22%3a%22526638ba-6af3-4b0f-a532-a1a511f4ac80%22%2c%22Oid%22%3a%22a5ed84b8-5af1-42c6-9f8d-240f23a5d997%22%7d)

Chair: USyd
Minute taker: UCL
Previous meeting: https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15 and [minutes](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1907418210).
Recording: [here](https://youtu.be/WQqMvZD6zRc)
Present:
Apologies:

**AGENDA**

@OpenSourceMycetoma/corecontrib please flag up any key issues ahead of the meeting, and please note any apologies above.

### **In vitro** screening**

- [ ] @MA-Jjingyi @marijschippers to report on any _in vitro_ or _in vivo_ screening that has taken place since the last meeting

### **Series 1 - Fenarimols**
- [ ] Final Molecules/SAR Gaps (summarised [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/5#issuecomment-1530752314). Latest status was described in previous meeting (#14). @fantasy121 has added a [new SAR diagram](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1905666076), also to the paper.

- [ ] @dosreic to investigate whether it is possible to have SCYX0001294212 EPL-BS0121 and SCYX0001315839 EPL-BS0143 shipped from TCG to Wendy.

- [x] @fantasy121 has added the [five compounds tested](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/12#issuecomment-1828164980) to the Master List and generated MyOS codes and sent those codes to @MA-Jjingyi and/or @marijschippers to ensure data can be properly reported. Shown [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1905371835). Have they been reported?

- [ ] @MA-Jjingyi to advise whether more data coming on these compounds

**Fenarimol Paper**

Most recent file version on Dropbox is: _Fenarimol Paper January 29 V2.3_ edited last Feb 11th 2024.

- [x] @fantasy121 and @dmitrij176 completed all assignments to them on experimental?
- [ ] @fantasy121 and @dmitrij176 What is known of related structures inhibiting CYP51, i.e. how do our results compare to what is known of Cyp51 inhibition?
- [ ] Compound numbering: use MyOS codes, but can use other numbers for compounds without those codes.

**Highlighting recent hits in this series**: from @MA-Jjingyi latest data, it would be helpful to have a diagram with structures. MYOS00510 and MYOS00518 were hits? Do recently-tested compounds need to be incorporated in the fenarimol manuscript? New SAR diagrams ideally need to be added to the wiki with codes, or we risk missing key insights from the new data.

Examples (are there others?):
[Data from Sept 21](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/files/12684110/26092023.MyctOS.meeting.-MA.pptx)

[ ] Modelling: @meh-cyprian to proceed to try to model fenarimol compounds in potential protein target (described [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/68#issuecomment-1546869698) or to clarify what more data are needed. Aim is to better understand the SAR via docking vs homology model of protein. @gemmaturon and @miquelduranfrigola presented their work that was done when visiting @meh-cyprian. 

### **Siderophores:**
Fluoroscent siderophore was tested in the larvae in the last weeks of the season.

- [x] @wwjvdsande to process the data to correct for autofluorescence. In the absence of this being on a wiki, maintain link with [this issue](https://github.com/OpenSourceMycetoma/What-other-molecules-to-screen/issues/10). <-- what were the outcomes of this testing?

### **Series 2 - Aminothiazoles**
- [x] Update from @KlementineJBS from the [schools meeting](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/17)? --> discussion was on which molecules where going to be made next.

Molecules made by UCL MSc cohort (23 entries) were shipped to Erasmus MC for testing. Data were summarised by @eloizidou [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1905479573). Also Whitgift compound (MYOS_0590_00_01). There were some slightly confusing data: some duplicate compounds have had different results when tested twice. What to do? Generally, compounds not very active. Next steps potentially double halogenation on right hand ring?

What is the mechanism of action related to this chemotype in the literature? Should we try testing with itraconazole to see if there is a synergistic effect – if there is, at least we’ll know that the aminothioazoles have a different MOA (i.e. do not work by inhibiting CYP451)

- [x] @MA-Jjingyi to report back on these data, potentially with update from Erika Loizidou (UCL). Note that [the current SAR page](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Structure-Activity-Relationships) is out of date and [this one](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Overall-summary) should be used? (Great job keeping this updated @KlementineJBS !)

@KlementineJBS wrote a guide on the [Wiki](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki) on how to share compounds in a way that will hopefully prevent duplication of both compounds themselves and MYOS codes. Also posted some compounds to be made next [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/19).

- [ ] @AndyBishopSevenoaks @JuliaSarju are there any samples likely to be incoming? <-- update from @P-Rayner was posted [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/23) and @KlementineJBS was in touch with @P-Rayner about shipping etc. @JuliaSarju and @P-Rayner have now sent through some compounds from Uni of York which have arrived at Erasmus, see https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/23. The aminothiazoles have MYOS codes already.
- [ ] @dosreic to try to secure samples related to this paper https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11 ?

**Series 5 - Benzimidazoles**
Good potencies were observed for recent compound batches of benzoxazoles (e.g. [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/82#issuecomment-1325150305)). These resemble the benzimidazoles which have shown potent in vivo efficacy.

Testing is ongoing. So far MYOS00527 was the only hit. @AndreaOtago conveyed [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1905575213) that the data are now public domain. <-- any learnings? Three of the compounds, UO17, UO22 and UO24, are eligible for in vivo screening later in the year?

Some oxazoles will be tested against _Falciformispora senegalensis_ too (by whom?). This series will be evaluated _in vivo_ in the new larval season <-- is this still to be done?

More benzoxazoles: @AndreaOtago says that the CHEM 305 students will be making more benzoxazoles in April 2024 as part of their lab project. @dosreic suggested doing some PK 'SAR' follow up analogues so this could inform both DNDi's project and this project. @dosreic to follow up the DMPK results.

- [ ] @AndreaOtago and @dosreic to update on planned designs and whether other students could make additional compounds using the same approach?

Would still be useful to know whether additional samples could be obtained from other labs.
- [x] @memm0740 updated on the synthesis carried out [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/7#issuecomment-1622784020) <-- Can this be added to the wiki by a member of the Sydney team, so we can close this action item?
- [x] @memm0740 to post link to raw data on ELN <-- can this please be put on the wiki by a member of the Sydney team?

### **Series 6: ketoximes**
Latest compound shipment https://github.com/OpenSourceMycetoma/Series-6-Ketoximes/issues/5, to be tested by @MA-Jjingyi.

- [ ] @dmitrij176 to summarise latest series data in a diagram and compare with previous most-relevant data to reveal what has been learned.

Commercial oxiconazole nitrate (Z isomer) most potent so far. Compound MYOS00419 has not been tested - @wwjvdsande to check on this

@bebi78 had suggested evaluating different salts of the ketoximes, still of value for future. Perhaps this can go on the wiki under future plans? <-- outdated. Would be useful to capture on wiki and then delete from here.

### **Series 3: Tricyclics/Phenothiazines**
- [X] NEU-Curaxin compounds have been given MyOS codes and can be tested - Results/data is now in spreadsheet - a few compounds showed decent IC90 (E.G MYOS00632 and the absolutely gigantic MYOS00626) https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6
- [x] @P-Rayner to plan what compounds he wants to make with his students while we wait for bioassay results from first phenothiazine batch: https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/8

### **Global Health Priority Box***

This has been tested and reported by @MA-Jjingyi [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/12#issuecomment-1729421998). Three compounds were taken on to _in vivo_ testing. Outcome is some promise for compound MMV1804559, the structure of which is shown [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1905561111). This compound both prolonged larval survival and induced morphological changes in the grains (decreasing their size).

- [x] Should MMV1804559 be pursued further? Can we buy it, or analogs of it? Some preliminary discussion [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/15#issuecomment-1943554945).

### **Kinase inhibitor library.** 
The KCGS library was screened. Additional drugs of similar classes were sent by @bebi78 and screened by @marijschippers. In total 6 drugs from the KCGS appeared to be hits along with one from the package sent by @bebi78. 

- [x] Data to be reported and uploaded. <-- where summarised?

### **Bioinformatics**
- [ ] @osmanwa to generate a phylogenetic tree to work out relationships of various species to allow for potential repurposing of hits vs closely-related organisms. @TariqAyub to contribute to this?

### **Plant Extracts from Nigeria**

Further to the conversation [here](https://github.com/OpenSourceMycetoma/Adjuvant-Screen/issues/2) we need to establish

- [ ] Whether the extracts have been evaluated @wwjvdsande @MA-Jjingyi 

- [ ] How we assign codes to these samples @bebi78 

- [ ] Whether more samples are incoming and how we can obtain costs for shipment @nwezemeka @dosreic 

### **Misc updates**:

- [x] Jan 30th is World NTD Day - how should we mark this to spread the word? Amplification of socmed activity by @dosreic would be very good. Can be closed - activity was noted [here](https://github.com/OpenSourceMycetoma/Talks-Meetings-Publicity/wiki/Publicity-on-Themed-Days), so this can be removed.

- [ ] @mattodd has received DMPK measurements by Dundee. Compound selection took place in [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/8) - @dmitrij176 to post there the chemdraw and spreadsheet of the final list of compounds that was sent to Dundee so we can correlate data with structure.

- [x] @KlementineJBS to enter the data for [Rohan Davies' compounds](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/issues/84#issuecomment-1507518700) into the Master List. They need [MyOS codes](https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/The-Molecule-Numbering-Convention). <-- done? Can this be closed?

- [x] @MA-Jjingyi previously presented larval toxicity studies results from recent compound screening. Data were presented [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/12#issuecomment-1729421998), but how do we fold the data into the Master List and the various wikis? @KlementineJBS gave a summary [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/12#issuecomment-1746122774). Do we have a strategy for toxicity measurements more generally?

**Notes on screening methods**
- Imperative that all compounds shipped to Erasmus have clear MYOS codes or at very least are labelled as MycetOS compounds (with an institutional identifier).
- We need to make sure we can capture/keep track of SAR. Will trial a colour code system, where the biology team shades recently tested samples in yellow in the masterlist. Once a chemist has digested this data in some way, e.g. as in Series 2, the chemist should remove the yellow shading from the masterlist.
- How best to acquire tox data and capture in Master List?

### **Next Meetings**
March 26th 8 a.m. UK time ([Timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=3&day=26&hour=8&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240))

**Comment by miquelduranfrigola** [comment]
Thanks @mattodd and @MFernflower  - is there any action you need from us (Ersilia)? @meh-cyprian please let us know if you need anything from us at this stage. As you know, a ligand-centred model was built and is readily available.

**Comment by bebi78** [comment]
@wwjvdsande Because sporotrichosis was mentioned and @MFernflower suggested the DNDi compound fosravuconazole for testing, there are two papers dealing with ravuconazole (see links).
https://onlinelibrary.wiley.com/doi/10.1111/j.1439-0507.2009.01701.x
https://academic.oup.com/mmy/article/46/2/141/1040643

**Comment by bebi78** [comment]
@MFernflower Maybe @dosreic can provide some information about the future plans of DNDi with fosravuconazole and the chances of a possible trial with Brazilian sporotrichosis patients.

**Comment by MFernflower** [comment]
https://dndi.org/our-people/borna-nyaoke/ seems to be the clinical trial director for fosravuconazole 

 maybe @wwjvdsande can get the sporothrix researcher (I forgot her name) in contact?

**Comment by bebi78** [comment]
@MFernflower @wwjvdsande @MA-Jjingyi Our new sporotrichosis partners in Brazil have recently published a paper about niclosamide (see link).
https://link.springer.com/article/10.1007/s42770-024-01301-5
