### ISSUE TITLE
Monthly MycetOS meeting - 24th September 2024

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMycetoma/Monthly-zoom-meetings#26]
24th Sept 2024: chair: UCL, minute taker: ErasmusMC
Will be 8 a.m. UK/5 PM Sydney - [timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=9&day=24&hour=7&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240)

The Outlook invite can be found https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/2#issuecomment-1905476888

Location: https://uni-sydney.zoom.us/j/99281549497. In case of failure, use https://ucl.zoom.us/j/99789829423 and in case of double failure use [MycetOS meeting teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2I2MDcxZTgtYjZjOS00YTdmLTgwZTMtNWQ3OTc4NDY0MDNj%40thread.v2/0?context=%7b%22Tid%22%3a%22526638ba-6af3-4b0f-a532-a1a511f4ac80%22%2c%22Oid%22%3a%22a5ed84b8-5af1-42c6-9f8d-240f23a5d997%22%7d)

Chair: UCL 
Minute taker: Erasmus MC
Previous meeting: #25 
Recording of today's meeting: [here](https://youtu.be/rHaDuLK8afo)
Present: @bebi78 @dmitrij176 @AndreaOtago @DouniaEMC @KlementineJBS @MFernflower , Vijay, Tim
Apologies: @P-Rayner @eloizidou @mattodd 

AGENDA AND MINUTES

## Screening updates and Housekeeping

- [ ] Erasmus team (@KlementineJBS or @DouniaEMC) to update with any new results
- [ ] We had agreed to reduce the number of tabs in the Master List, and that if new tabs were created, a README is included, clarifying that the tab is for.
- [ ] @KlementineJBS to update on the changes to General-Start-Here and What-Molecules-To-Screen repositories. 
Modelling has been put [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/wiki/Protein-modelling) - would it better to move this to the Fenarimols page?
- [ ] @lferrins to send compounds for re-screening: MYOS626, 627 and 628, and curaxin 137 (not screened before). **Question:** will we be able to screen with < 5 mg?

## Series 1 - Fenarimols

- [x] @dmitrij176 or @fantasy121 to add structures for [these untested compounds](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/wiki/Desired-compounds). 
- [x] @fantasy121 to review and update https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/wiki/Desirable-Compounds-Not-Yet-Synthesised seems to be out of date, can anyone advise if this can be archived or updated?
- [ ] @mattodd to capture on wiki pages the desirable compounds identified in the Fenarimol paper, e.g. meta-substituted derivatives.
- [ ] @mattodd to submit the paper (after checking final list of To Dos [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/22#issuecomment-2176558905). 

## Series 2 - Aminothiazoles

- [ ] @eloizidou to report back on any literature work on MoA that has been carried out by students. @wwjvdsande has created a page to communicate about this more clearly (see [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Clues-to-MoA-from-Literature)). See below.
- [ ] @eloizidou to report on the new Whitgift target compound, and any relevant results from MSc cohort. See below.
- [ ] @dosreic to send through samples described [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11) - this was held up by need for an MTA, which has now been sorted!
- [ ] @fantasy121 to add his thesis to GitHub + add info on MOA from his thesis to relevant repositories
- [ ] @KlementineJBS has found a group that may have samples we should test (https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/28) and is asking for advice on which compounds and how to reach out.

## Series 3: Tricyclics/Phenothiazines

- [ ] @P-Rayner Peter has sent approximately 28 more phenothiazines from the Uni of York students. Have these been tested, and if yes, is there an SAR diagram? Data should be posted to an issue and incorporated into the [Series 3 wiki](https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/wiki/). Is it still true that the "tail" of this series seems to be fixed (based on 10.1021/acs.jmedchem.2c01767 and the weak potency of N-phenethylphenothiazine), but the "head" can be optimized?
- [ ] Last time 5 of these NEU/Curaxin compounds (MYOS00626, MYOS00627, MYOS00628, MYOS00631 and MYOS00632) had been screened for toxicity _in vivo_ by @marijschippers and shown low tox. Data are in the Master List, but this toxicity assessment needs adding to the wiki, then this action item can be removed.
- [ ] Curaxin-137 testing: Does @lferrins have any in stock? if not, it might just be fine to skip screening this compound as @P-Rayner and company are planning to make @MFernflower 's curaxin-137 scaffold hops soon.
- [ ] @lferrins to send whatever amount of compounds she has for MYOS626, 627 and 628 - even if less than 5 mg. 

## Series 5 - Benzimidazoles

- [ ] @MA-Jjingyi is drafting results into a paper. Any update?
- [ ] @AndreaOtago to updates on SAR, or new molecules incoming?
- [ ] One compound was very promising _in vitro _ and will move into toxicity screens soon, two have prolonged larval survival. Which compounds were these and has this testing been completed @MA-Jjingyi ?
- [ ] @AndreaOtago to ask a student to rename compounds as Series 5a/5b in Masterlist OR provide us with list of which compounds are which if possible?
- [ ] @AndreaOtago or anyone else to identify what compounds we would like to obtain for testing? May be possible to get some from Charlotte at ICL in NZ. 

## Series 6: ketoximes

- [x] @dmitrij176 to update on SAR diagrams for this series
- [ ] @dmitrij176 to summarise DMPK Dundee data and any learnings.

### Kinase Inhibitor Library

- First paper of this project has been sent for review. Lab is hoping that new postdoc starting next month will be able to develop Madurella mycetomatis knockout models which would make it a lot easier to validate and publish this kind of work 
- new student Dounia can potentially also use old data to look at other potential targets e.g. enzymes (which ones?)
- @mattodd and @wwjvdsande in discussions with UNC Chapel Hill collaborator about potential mechanism of action/target ID studies for the kinase hits.

## Other

- [ ] @mattodd and @dosreic to identify a pharma contact for MycetOS.
- [ ] @mattodd looking into the synthesis of [MMV1804559](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/blob/main/MMV1804559.jpeg). It is not commercially available, nor are there any known analogues, but getting it made by a third-party CRO once would hopefully make it straightforward to start making analogues that could impact all series.
- [ ] Wendy has been screening the 6000-member approved drugs library and can report back when done! An advantage: already have tox data.

# Next meeting 
22 October 2024: chair: ErasmusMC, minute taker: USyd

**Comment by eloizidou** [comment]
I have updated the page on the possible targets for aminothiazoles and uploaded a document that summarises the results from the MSc projects.
https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Clues-to-MoA-from-Literature

This is the next aminothiazole analogue that Whitgift students will be synthesising, starting next week and we need to provided them with one more analogue for after January.
![image](https://github.com/user-attachments/assets/f23c8b4f-c282-4acd-a840-8f8f739d42d3)

**Comment by eloizidou** [comment]
I am afraid I will not be able to join the meeting tomorrow because of the new MSc programme inductions, but I am happy to discuss the data at any other time prior to the meeting in October.

**Comment by P-Rayner** [comment]
Unfortunately, I have to send my apologies for tomorrow's meeting. Will provide an update when we have the students underway in the lab. Peter

**Comment by MA-Jjingyi** [comment]
The update of Series 5: new benzoxazoles were tested both in vitro and in vivo. MYOS527 was selected from in vitro (MM55, IC50 is 3.1; CBS197.79, IC50 is 2.3). but it didn't prolong MM55 infected larvae survival. all data was updated here https://github.com/OpenSourceMycetoma/series-5-benzimidazoles/issues/5#issue-2521662031. New SAR analysis is needed. 

we are writing the manuscript. We will send it to co-author to give us more help in chemical results and discussion.

**Comment by MA-Jjingyi** [comment]
![selectedcompounds from in vitro](https://github.com/user-attachments/assets/600fd38c-c690-4768-aac6-c61110d53059)
![survival curve](https://github.com/user-attachments/assets/fdf28ce7-f4d1-44a6-be5d-6279a35b2123)
Sorry for absent this meeting. Here, two figures are updated as the summary of Series 5. Please check.

**Comment by fantasy121** [comment]
Re: this item: @fantasy121 to review and update https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/wiki/Desirable-Compounds-Not-Yet-Synthesised seems to be out of date, can anyone advise if this can be archived or updated?

I had a look at the compounds in details. A few of these compounds have been tested. I noted their MYOS codes before. The likely reasons that the remainder of the compounds have not been further explored was because A) they were not explored by me because I was focussing on different motifs in the S1 scaffold (as per our current manuscript), and B) the SAR shows amine and amide motifs at the piperazyl positions to be generally inactive

![GitHub updates](https://github.com/user-attachments/assets/a7abad74-e10e-4e1c-b5b2-4f7ab956fac3)

**Comment by fantasy121** [comment]
Our current SAR understanding of this chemical space (from manuscript)

<img width="1087" alt="Screenshot 2024-09-24 at 4 23 12 PM" src="https://github.com/user-attachments/assets/777e9b8d-9860-4026-a965-c9e303263284">

**Comment by fantasy121** [comment]
@dmitrij176 Do you have anything to comment on these compounds? I can see that two of these compounds were ones you synthesised, perhaps there might have been plans to explore their derivatives too at some points?

@mattodd As for my end, I can confirm I have not explored synthesis of the above compounds, and will not be personally synthesising these. From my analysis of SAR, I don't think the pictured chemical spaces above should be prioritised in near-future synthesis, as we have not achieved any potent hits beyond the three carbamate compounds (green) and the morpholinyl and piperidyl analogues synthesised by Dmitrij (square box above).

**Comment by fantasy121** [comment]
Sorry I won't be able to make today's meeting. if there is anything else that is needed, please drop me a mention in the comments.

**Comment by DouniaEMC** [comment]
### Minutes 24 september 2024 Mycetos meeting

**Screening updates and Housekeeping**

Matt and Wendy are not able to join, so we will skip those points:

Klementine presents her results:
-	Did MIC determination
-	Pyridine ring is important and more compounds are being made to test
-	Most compounds were not toxic to larvae.
-	Compounds from the University of York that will be tested
-	Compounds from UCL that will be tested as well

The extra tabs in the master list will be deleted if no one says that it needed. If the extra tab is needed, add a README. 

In the General-Start-Here wiki, there is a page for interesting papers and theses. 

In the Potential projects map there are different issues created with problems that can be solved, but this part is not yet public. Let us know if you have a problem.

@lferrins was not in the meeting, don’t know if compounds are send for re-screening.
Matt has not finished everything, but he is working on it.

**Series 1 - Fenarimols**
Dimitri updated untested compounds with SMILES.
Matt has the final manuscript of the paper, if he is ready it will be submitted. 

**Series 2 –** 
Document with possible MoA of Aminothiazoles

**Series 3 –**
Primary results of the compounds sent by York were not very active. Focus is now shifted towards compounds more like the NEU-curaxins

Data from Marije, Dounia will put the toxicity data in the wiki

**Series 5 –**
Andrea needs to know what journal to aim for so she can change the formatting. Andrea’s undergrads will not make any more compounds for the year. Andrea will tell use in January what new compounds will be made in april/may.
Andrea has some compounds that are easy to make but is not able to make them herself. Who can make those compounds?
Andrea will put the compounds on the other compounds to screen repository. 

**Series 6 –**
Dimitri presents his SAR results
Last batch contain 40 compounds, most of them were positive
Conclusion: Big differences between isomers, E isomer is more potent that the Z isomer
Oxiconazole nitrate (Z) isomer shows the best IC50, second best is compound 104-(E). 

Vijay offered that if the activity data for these ketoxime derivatives are provided, he can do QSAR analysis using Pydescriptor. He can also do AI. 
Generate different document with ketoximes so Vijay can test them, he just needs IC50 and structures. 

Bernhard has a suggestion to search for pesticides compounds/groups that is antifungal and anti-larvae to get some collaboration for money.

**Comment by vijaymasand** [comment]
Hello to everyone,
If you want to perform QSAR, molecular docking, pharmacophore modeling, scaffold hopping, and/or molecular dynamic simulations, please let me know. 
For QSAR, just SMILES notations and MIC/IC50/EC50 data values are required. Using PyDescriptor, we can find out extremely hidden information for a series of molecules. Also, PyDescriptor provides unique and interpretable results.
From
Vijay

**Comment by MFernflower** [comment]
Hello Vijay, We have data indeed in a so called "master sheet" at http://tinyurl.com/MycetomaMols

It might not be in the best format for training an AI on but might be worth a try.

@vijaymasand
