### ISSUE TITLE
 Monthly MycetOS meeting - 22nd October 2024

### ISSUE THREAD

**Issue by KlementineJBS** [OpenSourceMycetoma/Monthly-zoom-meetings#27]
22nd Oct 2024: chair: UCL, minute taker: ErasmusMC
Will be 12 PM UK/10 PM Sydney - [timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=10&day=22&hour=11&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240)

The Outlook invite can be found https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/2#issuecomment-1905476888

Location: https://uni-sydney.zoom.us/j/99281549497. In case of failure, use https://ucl.zoom.us/j/99789829423 and in case of double failure use [MycetOS meeting teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_M2I2MDcxZTgtYjZjOS00YTdmLTgwZTMtNWQ3OTc4NDY0MDNj%40thread.v2/0?context=%7b%22Tid%22%3a%22526638ba-6af3-4b0f-a532-a1a511f4ac80%22%2c%22Oid%22%3a%22a5ed84b8-5af1-42c6-9f8d-240f23a5d997%22%7d)

Chair: UCL 
Minute taker: Erasmus MC
Previous meeting: #26 
Recording of today's meeting: 
Present: 

AGENDA AND MINUTES

## Screening updates and housekeeping 

- [x] most extraneous tabs on the [masterlist](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit?gid=518064767#gid=518064767) have been deleted - can Mickey or @wwjvdsande advise on whether the Kinase Library, MMV and EpiChem tabs are to be kept? --> the kinase and MMV tabs should be left. They give data on other compounds which were screened and can be mined if we need to find comparator molecules. E.g. benzimidazoles were also present in the MMV compounds screened
- [ ] @KlementineJBS to share results in relevant sections

## Series 1 - Fenarimols 

- [ ] @mattodd to capture on wiki pages the desirable compounds identified in the Fenarimol paper, e.g. the meta-substituted derivatives.
- [ ] @mattodd to submit the paper (after checking final list of To Dos [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/22#issuecomment-2176558905). 

## Series 2 - Aminothiazoles 

- @KlementineJBS can share finalised IC50 results / they have been added to the [SAR page](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Overall-summary) and masterlist
- Uni of York and Whitgift compounds not finalised, but have similar MICs - raw data/ongoing work can be found [here](https://github.com/KlementineJBS/USYD_PhD_ELN/issues/241)
- @eloizidou to report back on any literature work on MoA that has been carried out by students. @wwjvdsande has created a page to communicate about this more clearly (see [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Clues-to-MoA-from-Literature)). See below.
- [ ] @fantasy121 to add his thesis to GitHub + add info on MOA from his thesis to relevant repositories
- @KlementineJBS has found a group that may have samples we should test (https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/28) and is asking for advice on which compounds and how to reach out.
- [ ] has @dosreic been able to send the samples described  [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11) ?
- [x] @P-Rayner to give update on the group of students who are making aminothiazoles
## Series 3 - Phenothiazines 

- very few hits from high-concentration testing of Uni of York's latest batch (see [here](https://github.com/KlementineJBS/USYD_PhD_ELN/issues/241) - results will be finalized within 1-2 weeks)
- [x] @DouniaEMC to add toxicity data for NEU/Curaxin compounds to Wiki 
- [ ] are @P-Rayner and co still planning on making the curaxin-137 scaffold hops as suggested by @MFernflower ?
- [x] has @lferrins been able to send any more MYOS626, 627 and 628?

## Series 5 - Benzimidazoles and benzoxazoles 

- any updates from @MA-Jjingyi or @AndreaOtago on the paper? Ma posted an update about the SAR/results in #26
- Andrea needs to know what journal we want to aim this paper at (for formatting/references)
- [x] Klementine to rename compounds as Series 5a/5b in masterlist 
- [x] has @AndreaOtago been able to make a list/figure of desired compounds? These can be posted as an issue on the Series 5 repository OR on the What-molecules-to-screen repository (and then shared to the "Potential projects" page [here](https://github.com/orgs/OpenSourceMycetoma/projects/2) --> currently private, needs to be unlocked by @mattodd <-- this has been done, now public.

## Series 6 - Ketoximes

- last meeting, Dmitrij presented his SAR findings. Majors conclusions are: big differences between isomers, E isomer is more potent that the Z isomer, Oxiconazole nitrate (Z) isomer shows the best IC50, second best is compound 104-(E). The conclusions and diagrams need to be added to the Series 6 wiki, e.g. [here](https://github.com/OpenSourceMycetoma/Series-6-Ketoximes/wiki/SAR-analysis-and-series-development).
- [ ] Dmitrij to share thesis [here](https://github.com/OpenSourceMycetoma/General-Start-Here/wiki/Papers-and-theses) when finalised 

## Biology 

- updates from @DouniaEMC at Erasmus MC
- Tim to update on collaboration with UNC Chapel Hill

## General 

- Vijay offered that if the activity data for these ketoxime derivatives are provided, he can do QSAR analysis using Pydescriptor. He can also do AI runs.
- we need to generate different document with ketoximes so Vijay can test them, he just needs IC50 and structures. Can we have volunteers to generate these for each series? 
- @bebi78 suggested looking into agricultural fungicides for new compounds - this could perhaps lead to a collaboration and be a possible source of funding. Who can look into this?

## Next meeting 

26 November 2024: chair: USyd, minute taker: UCL
8 a.m. London, 9 a.m. Europe, 7 p.m. Sydney [Timezones](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=11&day=26&hour=8&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240)

**Comment by KlementineJBS** [comment]
We are joining on the UCL zoom link today

**Comment by MFernflower** [comment]
The four series 3 compounds that we requested more of from Lori:

![307403277-24830bf9-8b2f-4a79-9bca-e62b658fe6c1](https://github.com/user-attachments/assets/cc104929-33cb-4bfa-ab80-4cd82507b740)
![342703461-12ef399d-dc5f-4376-b1ca-2efa293f514a](https://github.com/user-attachments/assets/d91292a3-e60b-478c-92ed-a5f18ba9b55d)

**Comment by eloizidou** [comment]
[Group project_summary of findings.pptx](https://github.com/user-attachments/files/17475811/Group.project_summary.of.findings.pptx)
This the summary of activities of aminothiazole analogues against HDAC, 20S proteasome and PI3K enzymes from the UCL MSc projects this summer.

**Comment by bebi78** [comment]
@KlementineJBS @P-Rayner Here is the already tested series 2 amine compound I mentioned in the meeting, available by reductive amination (via Schiff base intermediate).  

![series2 reductive amination](https://github.com/user-attachments/assets/38cd3fda-24fb-43dc-a9ba-7eff551f1a21)

**Comment by MFernflower** [comment]
@OpenSourceMycetoma/corecontrib Have N-alkylated aminothiazoles been tried? E:G
![N-ethyl-(5-chloro-N- 4-(pyridin-2-yl)-1,3-thiazol-2-yl pyridin-2-amine)](https://github.com/user-attachments/assets/aa966187-f226-4d3b-9c78-b0256d65f5f3)

**Comment by MFernflower** [comment]
2-(Methylamino)pyridine seems to be commercially available so this might be good target for highschool to make?

@KlementineJBS 

![image](https://github.com/user-attachments/assets/f2524693-ab52-4171-a960-92e440421ddc)

**Comment by bebi78** [comment]
@MFernflower If N-alkyl derivatives are active, it would pave the way to conjugate chemistry, e.g. conjugates with other antifungals, siderophores, or with dyes to identify targets, via alkyl linkers. Simple amides and sulfonamides might also be interesting then. Maybe docking can already provide a hint at the relevance of NH vs N-alkyl.

**Comment by MFernflower** [comment]
tagging @P-Rayner and @eloizidou so they can see this too

**Comment by vijaymasand** [comment]
Hello everyone,
I have some new results that I intended to share during the October meeting. However, I couldn’t find any details about the meeting schedule, so I wasn’t able to attend. Could someone please let me know how I can receive updates about future meetings in advance? 
Thank you!
From
Vijay

**Comment by bebi78** [comment]
@vijaymasand Hello, there is the Roster Monthly Meetings issue in the Monthly-Zoom-Meetings section which shows all meeting dates for this year. And the Agenda and Minutes ´´comment´´ of each meeting shows info for the next meeting at the bottom.

**Comment by KlementineJBS** [comment]
# Minutes 

Chair: UCL 
Minute taker: Erasmus MC
Previous meeting: #26 
Recording of today's meeting: @mattodd 
Present: @mattodd @bebi78 @KlementineJBS @MFernflower @wwjvdsande @DouniaEMC @eloizidou @P-Rayner @timjhb  and Kimberly Eadie (Erasmus MC)

## Housekeeping 

- all tabs remaining on masterlist as of 22-10-24 are to be kept, as they represent various compound libraries 

## Series 1 - Fenarimols 

- Mat is finishing off a few fiddly bits on the paper but it will be submitted soon
- [ ] @mattodd to capture on wiki pages the desirable compounds identified in the Fenarimol paper, e.g. the meta-substituted derivatives

## Series 2 - Aminothiazoles 

- Klementine has added IC50 data to masterlist and [SAR page](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Overall-summary) for compounds made by USyd 
- testing of compounds from UCL and Uni of York is ongoing - should be complete by Nov meeting
- [ ] @KlementineJBS to add aminothiazole sent by Bernhard to SAR page 
- Whitgift is working on the fluoro analogue listed in the SAR and Uni of York is purifying a few compounds from their last batch - these are indicated in BLUE on the SAR page 
- [ ] the structures of the compounds currently being made by Uni of York should be added to the SAR page too - has @P-Rayner already shared these on GitHub?
- [ ] can someone follow up with @dosreic on the samples described [here](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11) ?
- [ ] @KlementineJBS to draft email and send to Mat re: requesting compounds from the [Pieroni group](https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/28)

### Results of enzyme assays 

- presented by Erika, slides here [Group.project_summary.of.findings.pdf](https://github.com/user-attachments/files/17539601/Group.project_summary.of.findings.pdf)
- **in brief:** tested a range of aminothiazoles against HDAC, PI3K and 20S proteasome
- for HDAC: compounds all inhibited enzyme at 25 uM but almost all had reduced activity at 100 uM. Could be due to solubility issues but Erika felt this was unlikely due to nature of the assay. May be due to a biphasic response caused by compounds binding to allosteric pocket. 
- in docking studies, compounds generally had better affinity for human enzyme vs fungal model 
- the N of the nitro group on MYOS429 had a strong interaction with the Zn ion in the enzyme - however, MYOS429 had no activity against the fungus 
- for 20S proteasome: no compounds showed inhibition and docking analysis showed only weak affinity. Will probably not be explored further
- for PI3K: compounds all produced moderate inhibition but this was generally not dose-dependent. The experiment had high error margins and needs to be repeated, possibly by UCL students
- docking studies predict that aromatic groups on left hand bromoketone side will have stronger binding 
- overall: would like to test some amides, more compounds with aromatic groups on left hand side, and compounds with 2 x N on right hand thiourea side. Some of these already exist and some are being worked on by Uni of York at the moment 

## Series 3 - Phenothiazines 

- Dounia has uploaded toxicity data for MYOS626-628, 631 and 632 [here](https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6#issuecomment-2428496181)
- @P-Rayner may be able to make more of MYOS626-628 with students if Lori cannot send more 
- generally have started working on tricyclics 
- very few hits from high-concentration testing of Uni of York's latest batch - results should be finalised by Nov meeting 

## Series 5 - Benzimidazoles and benzoxazoles 

- [x] @KlementineJBS to update masterlist with series 5a/5b notation <-- Series 5a = benzimidazoles, series 5b = benzoxazoles
- [ ] @AndreaOtago to work on SAR - does she need any further data/anything to be sent again from Erasmus MC? alternatively, if she doesn't have time to work on this, can someone else help?
- [x] @KlementineJBS to check MMV box for other benzaxoles - previously, Erasmus MC team requested benzimidazoles, but not benzoxaoles <-- listed as an issue [here](https://github.com/OpenSourceMycetoma/series-5-benzimidazoles/issues/6)

## Series 6 - Ketoximes 

- Dmitrij still working on SAR and paper, will share when it is completed 

## Other business 

- Dounia will be testing a compound library from MedChemExpress that contains antifungals, fungicides and herbicides
- Tim is preparing the lysate for the kinase assay with UNC Chapel Hill 
- Tim could potentially look out for connections with agrochemical companies who may be interested in our compounds as pesticides - they want compounds that kill larvae!
- Vijay offered that if the activity data for these ketoxime derivatives are provided, he can do QSAR analysis using Pydescriptor. He can also do AI runs.
- we need to generate different document with ketoximes so Vijay can test them, he just needs IC50 and structures. Can we have volunteers to generate these for each series?

**Comment by KlementineJBS** [comment]
@vijaymasand the roster that Bernhard mentioned can be found [here](https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/2). We usually create a new issue for the meeting a few days beforehand, but the Zoom links don't change so you can always access them from a previous meeting (like this one)

**Comment by vijaymasand** [comment]
Good morning to everyone
Thank you all for your replies. I look forward to attending the meeting scheduled for November 2024.
From
Vijay

**Comment by dosreic** [comment]
Hi everyone,

It would be great to have a list of compounds from that paper, so I could check their availability and send them to Erasmus.

Discovery of Substituted Di(pyridin-2-yl)-1,2,4-thiadiazol-5-amines as Novel Macrofilaricidal Compounds for the Treatment of Human Filarial Infections | Journal of Medicinal Chemistry<https://pubs.acs.org/doi/10.1021/acs.jmedchem.2c00960>

Best wishes,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 21 96672 9043 | ***@***.******@***.***>
dndi.org

[A close up of orange letters  Description automatically generated]

De: Klementine Burrell-Sander ***@***.***>
Enviada em: segunda-feira, 28 de outubro de 2024 05:49
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly MycetOS meeting - 22nd October 2024 (Issue #27)

Minutes

Chair: UCL
Minute taker: Erasmus MC
Previous meeting: #26<https://github.com/OpenSourceMycetoma/Monthly-zoom-meetings/issues/26>
Recording of today's meeting: @mattodd<https://github.com/mattodd>
Present: @mattodd<https://github.com/mattodd> @bebi78<https://github.com/bebi78> @KlementineJBS<https://github.com/KlementineJBS> @MFernflower<https://github.com/MFernflower> @wwjvdsande<https://github.com/wwjvdsande> @DouniaEMC<https://github.com/DouniaEMC> @eloizidou<https://github.com/eloizidou> @P-Rayner<https://github.com/P-Rayner> , Tim Baltussen and Kimberly Eadie (Erasmus MC)

Housekeeping

  *   all tabs remaining on masterlist as of 22-10-24 are to be kept, as they represent various compound libraries

Series 1 - Fenarimols

  *   Mat is finishing off a few fiddly bits on the paper but it will be submitted soon
  *   [ ] @mattodd<https://github.com/mattodd> to capture on wiki pages the desirable compounds identified in the Fenarimol paper, e.g. the meta-substituted derivatives

Series 2 - Aminothiazoles

  *   Klementine has added IC50 data to masterlist and SAR page<https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/wiki/Overall-summary> for compounds made by USyd
  *   testing of compounds from UCL and Uni of York is ongoing - should be complete by Nov meeting
  *   [ ] @KlementineJBS<https://github.com/KlementineJBS> to add aminothiazole sent by Bernhard to SAR page
  *   Whitgift is working on the fluoro analogue listed in the SAR and Uni of York is purifying a few compounds from their last batch - these are indicated in BLUE on the SAR page
  *   [ ] the structures of the compounds currently being made by Uni of York should be added to the SAR page too
  *   [ ] can someone follow up with @dosreic<https://github.com/dosreic> on the samples described here<https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/11> ?
  *   [ ] @KlementineJBS<https://github.com/KlementineJBS> to draft email and send to Mat re: requesting compounds from the Pieroni group<https://github.com/OpenSourceMycetoma/Series-2-Aminothiazoles/issues/28>

Results of enzyme assays

  *   presented by Erika, slides here Group.project_summary.of.findings.pdf<https://github.com/user-attachments/files/17539601/Group.project_summary.of.findings.pdf>
  *   in brief: tested a range of aminothiazoles against HDAC, PI3K and 20S proteasome
  *   for HDAC: compounds all inhibited enzyme at 25 uM but almost all had reduced activity at 100 uM. Could be due to solubility issues but Erika felt this was unlikely due to nature of the assay. May be due to a biphasic response caused by compounds binding to allosteric pocket.
  *   in docking studies, compounds generally had better affinity for human enzyme vs fungal model
  *   the N of the nitro group on MYOS429 had a strong interaction with the Zn ion in the enzyme - however, MYOS429 had no activity against the fungus
  *   for 20S proteasome: no compounds showed inhibition and docking analysis showed only weak affinity. Will probably not be explored further
  *   for PI3K: compounds all produced moderate inhibition but this was generally not dose-dependent. The experiment had high error margins and needs to be repeated, possibly by UCL students
  *   docking studies predict that aromatic groups on left hand bromoketone side will have stronger binding
  *   overall: would like to test some amides, more compounds with aromatic groups on left hand side, and compounds with 2 x N on right hand thiourea side. Some of these already exist and some are being worked on by Uni of York at the moment

Series 3 - Phenothiazines

  *   Dounia has uploaded toxicity data for MYOS626-628, 631 and 632 here<https://github.com/OpenSourceMycetoma/Series-3-Phenothiazines/issues/6#issuecomment-2428496181>
  *   @P-Rayner<https://github.com/P-Rayner> may be able to make more of MYOS626-628 with students if Lori cannot send more
  *   generally have started working on tricyclics
  *   very few hits from high-concentration testing of Uni of York's latest batch - results should be finalised by Nov meeting

Series 5 - Benzimidazoles and benzoxazoles

  *   [ ] @KlementineJBS<https://github.com/KlementineJBS> to update masterlist with series 5a/5b notation
  *   [ ] @AndreaOtago<https://github.com/AndreaOtago> to work on SAR - does she need any further data/anything to be sent again from Erasmus MC? alternatively, if she doesn't have time to work on this, can someone else help?
  *   [ ] @KlementineJBS<https://github.com/KlementineJBS> to check MMV box for other benzaxoles - previously, Erasmus MC team requested benzimidazoles, but not benzoxaoles

Series 6 - Ketoximes

  *   Dmitrij still working on SAR and paper, will share when it is completed

Other business

  *   Dounia will be testing a compound library from MedChemExpress that contains antifungals, fungicides and herbicides
  *   Tim is preparing the lysate for the kinase assay with UNC Chapel Hill
  *   Tim could potentially look out for connections with agrochemical companies who may be interested in our compounds as pesticides - they want compounds that kill larvae!
  *   Vijay offered that if the activity data for these ketoxime derivatives are provided, he can do QSAR analysis using Pydescriptor. He can also do AI runs.
  *   we need to generate different document with ketoximes so Vijay can test them, he just needs IC50 and structures. Can we have volunteers to generate these for each series?

**Comment by MFernflower** [comment]
I assume we are looking for the two compounds present in the abstract image
of the paper! @dosreic

**Comment by dosreic** [comment]
I checked and we don’t have compound #1 in stock, but I selected a few more to send.


Entry from the paper

#DNDI

47

DNDI0003389167

4

DNDI0003948478

5

DNDI0003948389

17

DNDI0003948159

33

DNDI0003948417

45

DNDI0003948427

55

DNDI0003948184

Will contact Wendy for the shipment.

Best,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 21 96672 9043 | ***@***.******@***.***>
dndi.org

[A close up of orange letters  Description automatically generated]

De: MFernflower ***@***.***>
Enviada em: segunda-feira, 28 de outubro de 2024 13:02
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly MycetOS meeting - 22nd October 2024 (Issue #27)

I assume we are looking for the two compounds present in the abstract image
of the paper! @dosreic

**Comment by MFernflower** [comment]
Can you please post structures when you get a chance @dosrec

**Comment by dosreic** [comment]
Here they go:

***@***.***

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 21 96672 9043 | ***@***.******@***.***>
dndi.org

[A close up of orange letters  Description automatically generated]

De: MFernflower ***@***.***>
Enviada em: terça-feira, 29 de outubro de 2024 14:44
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly MycetOS meeting - 22nd October 2024 (Issue #27)

Can you please post structures when you get a chance @dosrec

**Comment by MFernflower** [comment]
@dosreic the image did not upload

**Comment by dosreic** [comment]
Hi everyone, let me know if this is enough:

#DNDI
SMILES
DNDI0003389167
CC(C)Oc1ccc(nc1)-c1nsc(n1)Nc1ncccc1N(C)C(=O)C
DNDI0003948478
Cc1cccnc1Nc1nnc(s1)-c1ccc(cn1)OC1CCOCC1
DNDI0003948159
CC(C)Oc1cnc(cc1C(=O)N(C)C)-c1nsc(n1)Nc1ncccc1C
DNDI0003948417
CC(C)Oc1cc(ncc1C(F)(F)F)-c1nsc(n1)Nc1ncccc1N(C)C
DNDI0003948427
CN(C(=O)C)c1ccc(nc1)-c1nsc(n1)Nc1ncccc1C
DNDI0003948184
CC(C)Oc1ccnc(c1)-c1nsc(n1)Nc1ncc(cc1N(C)C(=O)C)C(F)(F)F

Cheers,
Luiza

Luiza Cruz, PhD I Drug Discovery Coordinator
Drugs for Neglected Diseases initiative (DNDi)
Rua São José 70 – Sala 601 - Centro | ZIP 20010020 Rio de Janeiro | Brazil
M: +55 21 96672 9043 | ***@***.******@***.***>
dndi.org

[A close up of orange letters  Description automatically generated]

De: MFernflower ***@***.***>
Enviada em: terça-feira, 29 de outubro de 2024 16:20
Para: OpenSourceMycetoma/Monthly-zoom-meetings ***@***.***>
Cc: Luiza Cruz ***@***.***>; Mention ***@***.***>
Assunto: Re: [OpenSourceMycetoma/Monthly-zoom-meetings] Monthly MycetOS meeting - 22nd October 2024 (Issue #27)


@dosreic<https://github.com/dosreic> the image did not upload

**Comment by MFernflower** [comment]
Looks good thank you!

**Comment by eloizidou** [comment]
The results from the solubility studies of  two aminothiazole analogues have been completed:
<img width="202" alt="MYOS600" src="https://github.com/user-attachments/assets/a7335a66-94fb-482a-a4d3-4aae330268ba">
MYOS0600 < 2.94 uM; below LOQ (Limit Of Quantification)
![MYOS605](https://github.com/user-attachments/assets/08df4849-e097-44f3-a7ea-87a380b660b3)
MYOS605 = 109.9 uM
The method followed is explained in the attachment.
[University College London Solubility Cover Report November 27, 2024.pdf](https://github.com/user-attachments/files/17961052/University.College.London.Solubility.Cover.Report.November.27.2024.pdf)
[CLND Solubility Results_2024-11-11_Erica results.xlsx](https://github.com/user-attachments/files/17961053/CLND.Solubility.Results_2024-11-11_Erica.results.xlsx)
